# **Phase 11 — Specialized Topics.ipynb**

# **1️⃣ Masked Arrays (Handling Invalid / Missing Data)**

Definition
| Concept      | Meaning                                                |
| ------------ | ------------------------------------------------------ |
| Masked Array | Array that hides (ignores) certain values using a mask |
| Mask         | Boolean array (True = hidden, False = visible)         |

Think:

“This data exists… but ignore it in computation”

----
Why Use Masked Arrays?

- Handle invalid values (e.g., -999, errors)
- Clean datasets without deleting data
- Useful in scientific computing

1️⃣ Example 1: Basic Mask



In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, -999, 4, 5])

# np.ma.masked_equal automatically creates a mask
# where True is assigned to any element matching -999
masked = np.ma.masked_equal(arr, -999)
print(masked)

[1 2 -- 4 5]


Common Alternatives for Masking

| Function | Use Case |
| :--- | :--- |
| `np.ma.masked_greater(arr, 100)` | Masks any value above 100. |
| `np.ma.masked_less(arr, 0)` | Useful for masking negative numbers in physical measurements. |
| `np.ma.masked_invalid(arr)` | Automatically masks `NaN` (Not a Number) and `Inf` (Infinity). |
| `np.ma.masked_inside(arr, 10, 20)` | Masks values within a specific range (inclusive). |

---

**A quick tip:** If you ever need to get your "clean" data back into a regular array (for example, to export it), you can use `masked.filled(0)`. This will replace all the

`--` spots with `0` (or whatever value you choose).


2️⃣ Example 2: Manual Mask



In [3]:
arr = np.array([10, 20, 30, 40])

# Define the mask (True means 'Hidden/Invalid', False means 'Visible/Valid')
mask = [False, True, False, True]

masked = np.ma.array(arr, mask = mask)
# Create the masked array
print(masked)

[10 -- 30 --]


Key Concepts to Remember

| Concept | Description |
| :--- | :--- |
| **The Mask Logic** | **`True`** means the data is **masked** (hidden). **`False`** means the data is **unmasked** (visible). |
| **The Display** | Masked values are typically displayed as `--` in the console. |
| **Mathematical Impact** | If you run `masked.mean()`, NumPy will only calculate the average of `10` and `30` (Result: `20.0`). It ignores the `20` and `40`. |
| **Non-Destructive** | The original values (20 and 40) are still stored in memory under `masked.data`. They aren't gone; they are just "behind a curtain." |





3️⃣ Example 3: Mask Condition

In [4]:
arr = np.array([1, 2, 3, 4, 5])

masked = np.ma.masked_where(arr > 3, arr)

print(masked)

[1 2 3 -- --]


Why use `masked_where`?

This function is powerful because you can use complex logic to clean your data.

| Goal | Condition Code |
| :--- | :--- |
| **Mask Even Numbers** | `np.ma.masked_where(arr % 2 == 0, arr)` |
| **Mask Outliers** | `np.ma.masked_where(np.abs(arr - mean) > std, arr)` |
| **Mask specific range** | `np.ma.masked_where((arr > 2) & (arr < 5), arr)` |


----
Accessing the "Hidden" Parts
If you ever need to see the mask itself or the raw data behind it, you can use these attributes:
* `masked.mask`: Returns the boolean array `[False,False,False,True,True]`.
* `masked.data`: Returns the original raw array `[1, 2, 3, 4, 5]`.


4️⃣ Example 4: Computation Ignoring Mask

In [5]:
arr = np.array([1, 2, -999, 4])

masked = np.ma.masked_equal(arr, -999)

print(masked.mean())

2.3333333333333335


ignores `-999`

5️⃣ Example 5: Fill Masked Values

In [6]:
arr = np.array([1, 2, -999, 4])

masked = np.ma.masked_equal(arr, -999)

print(masked.filled(0))

[1 2 0 4]


6️⃣  Example 6: Mask + Arithmetic

In [7]:
# a has the middle element (2) hidden/masked
a = np.ma.array([1, 2, 3], mask=[0, 1, 0])
b = np.ma.array([10, 20, 30])

print(a + b)

[11 -- 33]


masked values stay masked

Arithmetic Outcomes Table

| Operation | Array A | Array B | Result | Logic |
| :--- | :--- | :--- | :--- | :--- |
| **Normal + Masked** | `[10, 20]` | `[1, --]` | `[11, --]` | Mask is preserved. |
| **Masked + Masked** | `[1, --]` | `[--, 10]` | `[--, --]` | If **either** is masked, the result is masked. |
| **Masked * 0** | `[--]` | `0` | `[--]` | Even multiplying by zero won't "unmask" the data. |

---

Masked Array Summary Table

| Feature          | Masked Array |
| ---------------- | ------------ |
| Missing Handling | Yes ✅        |
| Keeps Data       | Yes          |
| Ignores in Calc  | Yes          |
| Flexible         | Very         |


# **2️⃣ Handling Missing Values (np.nan)**

Definition

| Concept | Meaning                            |
| ------- | ---------------------------------- |
| np.nan  | Represents missing/undefined value |
| nanmean | Mean ignoring NaN                  |
| nanstd  | Std ignoring NaN                   |
-----
Important Rule

np.nan != np.nan (VERY IMPORTANT)

In [8]:
print(np.nan == np.nan)

False


1️⃣ Example 1: Create NaN

In [9]:
arr = np.array([1, 2, np.nan, 4])
print(arr)

[ 1.  2. nan  4.]


2️⃣ Example 2: Normal Mean (Problem ❌)



In [10]:
print(np.mean(arr))

nan


Output: nan

3️⃣ Example 3: nanmean (Correct ✅)

In [11]:
print(np.nanmean(arr))

2.3333333333333335


4️⃣ Example 4: Standard Deviation

In [12]:
print(np.nanstd(arr))

1.247219128924647


5️⃣ Example 5: Detect NaN

In [13]:
print(np.isnan(arr))

[False False  True False]


6️⃣ Example 6: Replace NaN

In [14]:
arr[np.isnan(arr)] = 0
print(arr)

[1. 2. 0. 4.]


7️⃣ Example 7: Remove NaN

In [19]:
arr = np.array([1, 2, np.nan, 4])

clean = arr[ ~np.isnan(arr)]

print(clean)

[1. 2. 4.]


8️⃣ Example 8: Multiple Operations

In [20]:
arr = np.array([1, np.nan, 3, np.nan, 5])

print(f"nanmean:\n{np.nanmean(arr)}\n")
print(f"nansum:\n{np.nansum(arr)}\n")
print(f"nanmax:\n{np.nanmax(arr)}\n")

nanmean:
3.0

nansum:
9.0

nanmax:
5.0



NaN Functions Table

| Function     | Meaning           |
| ------------ | ----------------- |
| np.nan       | Missing value     |
| np.isnan()   | Detect NaN        |
| np.nanmean() | Mean ignoring NaN |
| np.nanstd()  | Std ignoring NaN  |
| np.nansum()  | Sum ignoring NaN  |
| np.nanmax()  | Max ignoring NaN  |
-----

Complete NumPy NaN Function Reference

| Function | Meaning / Use Case | Result if NaN is Present |
| :--- | :--- | :--- |
| `np.isnan(x)` | **Detects NaN**: Returns `True` if the value is NaN. | Boolean mask |
| `np.nanmean(x)` | **Mean**: Calculates the average ignoring all NaNs. | Numerical average |
| `np.nansum(x)` | **Sum**: Adds elements together, treating NaNs as zeros. | Total sum |
| `np.nanstd(x)` | **Standard Deviation**: Calculates spread ignoring NaNs. | Std Deviation |
| `np.nanvar(x)` | **Variance**: Calculates variance ignoring NaNs. | Variance |
| `np.nanmin(x)` | **Minimum**: Returns the smallest non-NaN value. | Minimum value |
| `np.nanmax(x)` | **Maximum**: Returns the largest non-NaN value. | Maximum value |
| `np.nanargmin(x)` | **Index of Min**: Returns the index of the smallest non-NaN. | Index (Integer) |
| `np.nanargmax(x)` | **Index of Max**: Returns the index of the largest non-NaN. | Index (Integer) |
| `np.nanpercentile()`| **Percentile**: Computes q-th percentile ignoring NaNs. | Percentile value |
| `np.nanmedian()` | **Median**: Finds the middle value ignoring NaNs. | Median value |




# **🆚 Masked Arrays vs NaN**

Comparison Table
| Feature          | Masked Arrays   | NaN      |
| ---------------- | --------------- | -------- |
| Works with ints  | Yes ✅           | No ❌     |
| Flexible masking | Yes ✅           | No       |
| Built-in support | Medium          | Strong ✅ |
| Performance      | Slightly slower | Faster   |
| Simplicity       | Medium          | Easy ✅   |
----
# **When to Use What?**
| Situation                 | Use             |
| ------------------------- | --------------- |
| General ML/Data Analysis  | NaN ✅           |
| Complex masking rules     | Masked Arrays ✅ |
| Integer data with missing | Masked Arrays   |
| Speed critical            | NaN             |


-----
# **Real ML Insight (VERY IMPORTANT)**
Most libraries:
- Pandas
- Scikit-learn
- TensorFlow / PyTorch

👉 Prefer NaN approach

Masked arrays are used more in:

- Scientific computing
- Astronomy
- Physics datasets
----
# **FINAL SUMMARY**

| Topic          | Key Idea                  |
| -------------- | ------------------------- |
| Masked Arrays  | Hide values using mask    |
| np.nan         | Represent missing data    |
| nanmean/nanstd | Ignore missing values     |
| Mask vs NaN    | Flexibility vs simplicity |


# **TAKEAWAYS**

- ❗ `np.nan` is the industry standard
- ❗ Always use `nan*` functions
- ❗ Masked arrays = advanced control
- ❗ Missing data handling is critical in ML pipelines