# **Phase 7 — Stacking & Splitting**

The Idea

You are combining and breaking arrays
| Action    | Meaning        |
| --------- | -------------- |
| Stacking  | combine arrays |
| Splitting | divide arrays  |


Base Arrays

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8,9],
              [10,11,12]])

In [ ]:
print(f"a: \n{a}\n")
print(f"b: \n{b}\n")

a: 
[1 2 3]

b: 
[4 5 6]



In [ ]:
print(f"A: \n{A}\n")
print(f"B: \n{B}\n")

A: 
[[1 2 3]
 [4 5 6]]

B: 
[[ 7  8  9]
 [10 11 12]]



# **1️⃣ `np.vstack()` (Vertical Stack)**

Definition: Stack arrays row-wise (on top of each other)

1️⃣ 1D Example

In [ ]:
print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


2️⃣ 2D Example

In [ ]:
print(np.vstack((A, B)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


3️⃣ More Examples

In [ ]:
print(np.vstack((A, A)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
print(np.vstack((B, A)))

[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


**⚠️ Rule**

Arrays must have same number of columns

**Table**

| Input Shapes  | Result |
| ------------- | ------ |
| (3,) + (3,)   | (2,3)  |
| (2,3) + (2,3) | (4,3)  |


# **2️⃣ `np.hstack()` (Horizontal Stack)**

Definition: Stack arrays column-wise (side by side)

1️⃣ 1D Example

In [ ]:
print(np.hstack((a, b)))

[1 2 3 4 5 6]


2️⃣ 2D Example

In [ ]:
np.hstack((A, B))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

3️⃣ More Examples

In [ ]:
print(np.hstack((A, A)))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [ ]:
print(np.hstack((B, A)))

[[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]]


**⚠️ Rule**

Arrays must have same number of rows

**Table**
| Input Shapes  | Result |
| ------------- | ------ |
| (3,) + (3,)   | (6,)   |
| (2,3) + (2,3) | (2,6)  |


# **3️⃣ `np.concatenate()` (MOST FLEXIBLE)**

Definition: Join arrays along a specific axis

Syntax:

`np.concatenate((A, B), axis=0)`

EXAMPLES

1️⃣ Axis 0 (vertical)


In [ ]:
print(np.concatenate((A, B), axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


same as `vstack`

2️⃣ Axis 1 (horizontal)

In [ ]:
print(np.concatenate((A, B), axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


same as `hstack`

3️⃣ 1D Examples

In [ ]:
print(np.concatenate((a, b)))

[1 2 3 4 5 6]


4️⃣ More Advanced

In [ ]:
C = np.array([[100,200,300]])
print(C)

[[100 200 300]]


In [ ]:
print(np.concatenate((A, C), axis=0))

[[  1   2   3]
 [  4   5   6]
 [100 200 300]]


In [ ]:
print(np.concatenate((A, C), axis=1))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

**⚠️ Rules**

| Axis   | Requirement  |
| ------ | ------------ |
| axis=0 | same columns |
| axis=1 | same rows    |
--------------------------------
**Table**
| Code   | Meaning    |
| ------ | ---------- |
| axis=0 | vertical   |
| axis=1 | horizontal |
--------------------------------
**vstack vs hstack vs concatenate**
| Function    | Direction  | Equivalent |
| ----------- | ---------- | ---------- |
| vstack      | vertical   | axis=0     |
| hstack      | horizontal | axis=1     |
| concatenate | flexible   | both       |


# **4️⃣ `np.split()` (Split Arrays)**

Definition: Divide array into parts

1️⃣ 1D Example



In [ ]:
arr = np.array([1,2,3,4,5,6])
print(np.split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


2️⃣ Split at specific indices

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8])
np.split(arr1, [2,4])

[array([1, 2]), array([3, 4]), array([5, 6, 7, 8])]

3️⃣ 2D Examples

- 1️⃣ Split rows

In [ ]:
arr2 = np.arange(1,13).reshape(3,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(np.split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


- 2️⃣ Split columns

In [ ]:
print(np.split(arr2, 2, axis=1))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


4️⃣ More Examples

In [ ]:
print(np.split(arr2, [1,2]))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [ ]:
print(np.split(arr2, [2], axis=1))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


**⚠️ Rule**

Equal split required (unless using indices)

**Table**
| Code             | Meaning       |
| ---------------- | ------------- |
| split(arr,3)     | equal parts   |
| split(arr,[2,4]) | custom split  |
| axis=1           | split columns |


# **FULL COMBINED EXAMPLE**

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f"a array: \n{a}\n")
print(f"b array: \n{b}\n")

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print(f"A array: \n{A}\n")
print(f"B array: \n{B}\n")

# stacking
print(f"vstack: \n{np.vstack((A,B))}\n")
print(f"hstack: \n{np.hstack((A,B))}\n")

# concatenate
print(f"concatenate vertical: \n{np.concatenate((A,B), axis=0)}\n")
print(f"concatenate horizontal: \n{np.concatenate((A,B), axis=1)}\n")

# splitting
arr = np.arange(1,13)
print(f"splitting: \n{print(np.split(arr, 3))}\n")


a array: 
[1 2 3]

b array: 
[4 5 6]

A array: 
[[1 2 3]
 [4 5 6]]

B array: 
[[ 7  8  9]
 [10 11 12]]

vstack: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

hstack: 
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

concatenate vertical: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

concatenate horizontal: 
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
splitting: 
None



# **COMPARISON TABLE**
| Concept            | Function       | Use          |
| ------------------ | -------------- | ------------ |
| Vertical combine   | vstack         | add rows     |
| Horizontal combine | hstack         | add columns  |
| Flexible combine   | concatenate    | full control |
| Split equal        | split          | equal parts  |
| Split custom       | split(indices) | custom       |
----------------------------------
# **HOW TO THINK**
| Goal           | Use            |
| -------------- | -------------- |
| add rows       | vstack         |
| add columns    | hstack         |
| full control   | concatenate    |
| divide equally | split          |
| divide custom  | split(indices) |


# **Practice**
```
A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(2,3)

# 1. Stack vertically
# 2. Stack horizontally
# 3. Concatenate axis=0
# 4. Concatenate axis=1
# 5. Split into 2 parts
# 6. Split columns into 3 parts
```

In [ ]:
A = np.arange(1,7).reshape(2,3)
print(f"A:\n{A}\n")
B = np.arange(7,13).reshape(2,3)
print(f"B:\n{B}\n")

# 1. Stack vertically
print(f"Stack vertically:\n{np.vstack((A, B))}\n")

# 2. Stack horizontally
print(f"Stack horizontally:\n{np.hstack((A, B))}\n")

# 3. Concatenate axis=0
print(f"Concatenate axis=0:\n{np.concatenate((A, B), axis=0)}\n")

# 4. Concatenate axis=1
print(f"Concatenate axis=1:\n{np.concatenate((A, B), axis=1)}\n")

# 5. Split into 2 parts
print(f"Split A into 2 parts:\n{np.split(A, [2], axis=1)}\n")
print(f"Split B into 2 parts:\n{np.split(B, 2, axis=0)}\n")

# 6. Split columns into 3 parts
print(f"Split A columns into 3 parts:\n{np.split(A, 3, axis=1)}")

A:
[[1 2 3]
 [4 5 6]]

B:
[[ 7  8  9]
 [10 11 12]]

Stack vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Stack horizontally:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Concatenate axis=0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenate axis=1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Split A into 2 parts:
[array([[1, 2],
       [4, 5]]), array([[3],
       [6]])]

Split B into 2 parts:
[array([[7, 8, 9]]), array([[10, 11, 12]])]

Split A columns into 3 parts:
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


# **FINAL CHEAT SHEET**
| Category      | Tools          |
| ------------- | -------------- |
| Stack rows    | vstack         |
| Stack columns | hstack         |
| Flexible join | concatenate    |
| Split equal   | split          |
| Split custom  | split(indices) |


# **Before you go look at this method**

# **1️⃣ `np.dstack()` — Depth Stack (3D)**

Definition: Stack arrays along 3rd axis (depth)

Converts 2D → 3D

Example

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print(A,"\n")
print(B)

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]]


In [ ]:
print(A.shape)
print(B.shape)

(2, 3)
(2, 3)


In [ ]:
dstack = np.dstack((A, B))
print(dstack)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
print(dstack.shape)

(2, 3, 2)


Visualization:

- Rows = 2
- Columns = 3
- Depth = 2 arrays

Think of it like:

- stacking layers like a sandwich 🥪