# **Phase 4 — Array Operations**

The Idea

NumPy does operations:

- Element-wise (NOT like Python lists)
- Without loops (vectorization)
- With broadcasting (automatic expansion)

# **1️⃣ Arithmetic Operations (Element-wise)**

Base Arrays

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

1️⃣ Addition

In [2]:
print(a + b)

[11 22 33]


👉 Element by element:

`1+10, 2+20, 3+30`

2️⃣ Subtraction

In [3]:
print( b - a)

[ 9 18 27]


3️⃣ Multiplication

In [4]:
print(a * b)

[10 40 90]


4️⃣ Division

In [6]:
print(b / a)

[10. 10. 10.]


5️⃣ Power

In [7]:
print(a **2)

[1 4 9]


In [8]:
print(b ** 2)

[100 400 900]


6️⃣ Modulus

In [10]:
print(b % a)

[0 0 0]


**Table**

| Operation | Code   | Result     |
| --------- | ------ | ---------- |
| Add       | a + b  | [11 22 33] |
| Subtract  | b - a  | [9 18 27]  |
| Multiply  | a * b  | [10 40 90] |
| Divide    | b / a  | [10 10 10] |
| Power     | a ** 2 | [1 4 9]    |


# **2️⃣ Element-wise vs Python Lists (VERY IMPORTANT)**

In [13]:
# Python list
print([1,2,3] + [10,20,30])                      # [1,2,3,10,20,30] ❌
# NumPy
print(np.array([1,2,3]) + np.array([10,20,30]))  # [11 22 33] ✅

[1, 2, 3, 10, 20, 30]
[11 22 33]


👉 NumPy = math

👉 Python list = concatenation

# **3️⃣ Scalar Operations (Broadcasting starts here)**

In [14]:
a = np.array([1, 2, 3])

In [15]:
print(a + 5)
print(a * 2)
print(a - 1)
print(a / 2)

[6 7 8]
[2 4 6]
[0 1 2]
[0.5 1.  1.5]


👉 Scalar automatically applies to ALL elements

**Table**

| Code  | Result       |
| ----- | ------------ |
| a + 5 | add to all   |
| a * 2 | multiply all |
| a / 2 | divide all   |


# **4️⃣ Broadcasting**

Definition

Broadcasting: NumPy automatically expands arrays to match shapes

--------------------------

### ***Rule (MUST MEMORIZE)***

Two arrays are compatible if:

1- Same shape ✅

2- One dimension is 1 ✅

-------------------------------
1️⃣ Example 1: Vector + Scalar


In [16]:
a = np.array([1, 2, 3])

print(a + 10)

[11 12 13]


2️⃣ Example 2: 2D + Scalar

In [17]:
arr = np.array([[1,2,3],
                [4,5,6]])
print( arr + 10)

[[11 12 13]
 [14 15 16]]


3️⃣ Example 3: Row Broadcasting

In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])

row = np.array([10,20,30])

print(arr + row)

[[11 22 33]
 [14 25 36]]


row applied to EACH row

4️⃣ Example 4: Column Broadcasting

In [19]:
arr = np.array([[1,2,3],
                [4,5,6]])

col = np.array([[10],
                [20]])

print(arr + col)

[[11 12 13]
 [24 25 26]]


column applied to EACH column

5️⃣ Example 5: Different Shapes

In [20]:
a = np.array([[1,2,3]])
b = np.array([[1],[2],[3]])

print( a + b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


**Broadcasting Visualization**

| Shape A | Shape B | Result |
| ------- | ------- | ------ |
| (2,3)   | (3,)    | (2,3)  |
| (2,3)   | (2,1)   | (2,3)  |
| (1,3)   | (3,1)   | (3,3)  |


❌ Broadcasting Error

In [21]:
a = np.array([1,2,3])
b = np.array([1,2])

print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

❌ Error (shapes incompatible)


# **5️⃣ Element-wise Functions**

Built-in NumPy operations

1️⃣ Square root

In [22]:
a = np.array([1, 4, 9])

print(np.sqrt(a))

[1. 2. 3.]


2️⃣ Exponential

In [23]:
print(np.exp(a))

[2.71828183e+00 5.45981500e+01 8.10308393e+03]


3️⃣ Log

In [24]:
print(np.log(a))

[0.         1.38629436 2.19722458]


4️⃣ Absolute

In [25]:
print(np.abs([-1, -2, -3]))

[1 2 3]


5️⃣ Trigonometry

In [26]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098 -0.7568025   0.41211849]
[ 0.54030231 -0.65364362 -0.91113026]
[ 1.55740772  1.15782128 -0.45231566]


**Table**

| Function | Meaning      |
| -------- | ------------ |
| sqrt     | square root  |
| exp      | e^x          |
| log      | logarithm    |
| abs      | absolute     |
| sin/cos  | trigonometry |


# **FULL COMBINED EXAMPLE**

In [27]:
arr = np.arange(1,7).reshape(2,3)
print(f"{arr}\n")

row = np.array([10,20,30])
print(f"{row}\n")

col = np.array([[1],[2]])
print(f"{col}\n")

print(f"row broadcast: {arr + row}\n")   # row broadcast

print(f"column broadcast: {arr + col}\n")   # column broadcast

print(f"scalar: {arr * 2}\n")     # scalar

print(f"square root: {np.sqrt(arr)}\n")

[[1 2 3]
 [4 5 6]]

[10 20 30]

[[1]
 [2]]

row broadcast: [[11 22 33]
 [14 25 36]]

column broadcast: [[2 3 4]
 [6 7 8]]

scalar: [[ 2  4  6]
 [ 8 10 12]]

square root: [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]



# **COMPARISON TABLE**

| Concept      | Description              | Example    |
| ------------ | ------------------------ | ---------- |
| Arithmetic   | basic math               | a + b      |
| Scalar       | one value applied to all | a + 5      |
| Broadcasting | shape expansion          | arr + row  |
| Element-wise | operation per element    | a * b      |
| Functions    | math ops                 | np.sqrt(a) |

# **HOW TO THINK**

When solving:

| Situation        | Solution         |
| ---------------- | ---------------- |
| same shape       | direct operation |
| scalar           | auto broadcast   |
| row vs matrix    | broadcast row    |
| column vs matrix | broadcast column |


# **Practice**

```
arr = np.arange(1,13).reshape(3,4)

# 1. Add 5 to all elements
# 2. Multiply each row by [1,2,3,4]
# 3. Add column vector [[1],[2],[3]]
# 4. Take sqrt of all elements
# 5. Subtract row [10,20,30,40]
```

In [41]:
arr = np.arange(1,13).reshape(3,4)
print(f"{arr}\n")

# 1. Add 5 to all elements
print(f"{arr + 5}\n")

# 2. Multiply each row by [1,2,3,4]
arr1 = np.array([1, 2, 3, 4])
print(f"{arr * arr1}\n")

# 3. Add column vector [[1],[2],[3]]
arr2 = np.array([[1],[2],[3]])
print(f"{arr + arr2}\n")

# 4. Take sqrt of all elements
print(f"{np.sqrt(arr)}\n")

# 5. Subtract row [10,20,30,40]
arr3 = np.array([10, 20, 30, 40])
print(arr - arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]

[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]]

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]

[[ -9 -18 -27 -36]
 [ -5 -14 -23 -32]
 [ -1 -10 -19 -28]]


# **FINAL CHEAT SHEET**

| Category     | Tools                |
| ------------ | -------------------- |
| Arithmetic   | + - * / **           |
| Scalar       | arr + 5              |
| Broadcasting | row/column expansion |
| Functions    | sqrt, log, exp       |
| Element-wise | default behavior     |


# **Final Advice (VERY IMPORTANT)**

👉 If you ever write a loop like this:

In [43]:
arr = np.arange(1, 13).reshape(3, 4)
print(f"before using loop:\n {arr}\n")
for i in range(len(arr)):
    arr[i] = arr[i] + 5

print(f"after using loop:\n {arr}")

before using loop:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

after using loop:
 [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


**❌ STOP immediately**

✔ Replace with:

In [44]:
arr = np.arange(1, 13).reshape(3, 4)
print(f"{arr}\n")

print(arr + 5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
