# **Phase 3 — Indexing & Slicing**

**The Idea**

- Indexing = access specific elements

- Slicing = access ranges of elements

# **Base Arrays (We’ll use them everywhere)**


In [1]:
import numpy as np

In [2]:
# 1D
arr1 = np.array([10, 20, 30, 40, 50])
print(f"arr1: \n{arr1}\n")

# 2D
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(f"arr2: \n{arr2}")

arr1: 
[10 20 30 40 50]

arr2: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **1️⃣ 1D Indexing**

1️⃣ Access by position

In [3]:
print(arr1[0])
print(arr1[2])
print(arr1[-1]) # last element
print(arr1[-2])

10
30
50
40


2️⃣ Modify values

In [4]:
print(f"Before Modify values: {arr1[0]}")

arr1[0] = 100
print(f"After Modify values: {arr1[0]}")

Before Modify values: 10
After Modify values: 100


3️⃣ Multiple quick examples

In [5]:
print(arr1[1])
print(arr1[-3])
print(arr1[4])

20
30
50


# **Table**

| Code     | Meaning       | Result |
| -------- | ------------- | ------ |
| arr1[0]  | first element | 10     |
| arr1[-1] | last element  | 50     |
| arr1[2]  | index 2       | 30     |


# **2️⃣ 2D Indexing (Matrix Style)**

1️⃣ Basic format

`arr2[row, column]`

2️⃣ Examples

In [6]:

print(arr2[0, 0])
print(arr2[1, 2])
print(arr2[2, 1])

1
6
8


3️⃣ Access full row / column

In [7]:
print(arr2[0])     # first row → [1 2 3]
print(arr2[:, 1])  # second column → [2 5 8]
print(arr2[:, 0])  # first column → [1 4 7]

[1 2 3]
[2 5 8]
[1 4 7]


4️⃣ More variations

In [8]:
print(arr2[1, :])
print(arr2[:, 2])

[4 5 6]
[3 6 9]


# **Table**

| Code      | Meaning       | Result  |
| --------- | ------------- | ------- |
| arr2[0,0] | first element | 1       |
| arr2[1,2] | row 1 col 2   | 6       |
| arr2[0]   | first row     | [1 2 3] |
| arr2[:,1] | second column | [2 5 8] |


# **3️⃣ Slicing**
Syntax:

`array[start:stop:step]`

1️⃣ 1D Slicing Examples

In [12]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

[10 20 30 40 50]


In [11]:
print(arr1[1:4])
print(arr1[:3])
print(arr1[2:])
print(arr1[::2])
print(arr1[::-1]) # reverse → [50 40 30 20 10]

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


2️⃣ 2D Slicing Examples

In [13]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(arr2[0:2, 0:2])

[[1 2]
 [4 5]]


arr2[rows, columns, steps]

In [15]:
print(arr2[:, 1:3])

[[2 3]
 [5 6]
 [8 9]]


In [16]:
print(arr2[1:, :])

[[4 5 6]
 [7 8 9]]


In [17]:
print(arr2[::2, ::2])

[[1 3]
 [7 9]]


**Table**

| Code        | Meaning          |
| ----------- | ---------------- |
| arr[1:4]    | slice range      |
| arr[:3]     | start to index 3 |
| arr[::2]    | step 2           |
| arr[::-1]   | reverse          |
| arr2[:,1:3] | columns slice    |


# **4️⃣ Boolean Indexing**

The Idea

Filter data using conditions

1️⃣ Examples

In [18]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [22]:
print(arr[arr > 25])
print(arr[arr <= 30])
print(arr[arr % 20 == 0])

[30 40 50]
[10 20 30]
[20 40]


2️⃣ 2D Boolean

In [23]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(arr2[arr2 > 5])

[6 7 8 9]


3️⃣ Modify with condition

In [27]:
arr[arr > 30] = 0
print(arr)

[10 20 30  0  0]


**Table**
| Condition         | Result        |
| ----------------- | ------------- |
| arr > 25          | filter values |
| arr % 2 == 0      | even numbers  |
| arr[arr > 30] = 0 | modify        |


# **5️⃣ Fancy Indexing (Advanced)**

The Idea

Select specific indices manually

1️⃣ 1D Examples

In [29]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [33]:
print(arr[[0, 2, 4]])

[10 30 50]


In [34]:
print(arr[[3, 1]])

[40 20]


2️⃣ 2D Examples

In [36]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(arr2[[0,2]]) # row 0 and 2

[[1 2 3]
 [7 8 9]]


In [38]:
print(arr2[:, [0,2]])  # all rows & columns 0 and 2

[[1 3]
 [4 6]
 [7 9]]


3️⃣ Mixed

In [40]:
print(arr2[[0,1], [1,2]]) # [0,1] row 0 and column 1 & [1,2] row 1 and column 2

[2 6]


Explanation:

- (0,1) → 2

- (1,2) → 6

**Table**

| Code          | Meaning        |
| ------------- | -------------- |
| arr[[0,2]]    | select indices |
| arr2[[0,2]]   | select rows    |
| arr2[:,[0,2]] | select columns |


# **6️⃣ Extra Tools**

1️⃣ `np.where()`

In [41]:
arr = np.array([10, 20, 30, 40])
np.where(arr > 25)

(array([2, 3]),)

👉 returns indices

2️⃣ Replace using where

In [42]:
np.where(arr > 25, 1, 0)

array([0, 0, 1, 1])

3️⃣ `np.take()`

In [43]:
np.take(arr, [0,2])

array([10, 30])

4️⃣ np.put()

In [47]:
np.put(arr, [0,1], [99,88])
print(arr)

[99 88 30 40]


# **FULL COMBINED EXAMPLE**

In [56]:
arr = np.arange(1, 10).reshape(3,3)
print(f"{arr}\n")

# Indexing
print(f"{arr[1,2]}\n")

# Slicing
print(f"{arr[:,1]}\n")

# Boolean
print(f"{arr[arr > 5]}\n")

# Fancy
print(f"{arr[[0,2]]}\n")

# Where
print(f"{np.where(arr > 5)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

6

[2 5 8]

[6 7 8 9]

[[1 2 3]
 [7 8 9]]

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))


# **COMPARISON**

| Type     | Use Case       | Example    |
| -------- | -------------- | ---------- |
| Indexing | single value   | arr[0]     |
| Slicing  | range          | arr[1:4]   |
| Boolean  | condition      | arr[arr>5] |
| Fancy    | custom indices | arr[[0,2]] |


# **HOW TO THINK**
When you see a problem:

| Goal        | Use      |
| ----------- | -------- |
| One value   | indexing |
| Range       | slicing  |
| Filter      | boolean  |
| Custom pick | fancy    |



# **Practice**

```
arr = np.arange(20)

# 1. Get even numbers
# 2. Reverse array
# 3. Get elements from index 5 to 15 step 2
# 4. Replace values > 10 with -1
```

In [62]:
arr = np.arange(20)
print(f"{arr}\n")
# 1. Get even numbers
print(f"even numbers: {arr[arr % 2 == 0]}\n")

# 2. Reverse array
print(f"Reverse array: {arr[::-1]}\n")

# 3. Get elements from index 5 to 15 step 2
print(f"{arr[5:15:2]}\n")

# 4. Replace values > 10 with -1
print(f"{np.where(arr > 10 , -1, 0)}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

even numbers: [ 0  2  4  6  8 10 12 14 16 18]

Reverse array: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

[ 5  7  9 11 13]

[ 0  0  0  0  0  0  0  0  0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1]


# **FINAL CHEAT SHEET**
| Category | Tools            |
| -------- | ---------------- |
| Basic    | [], [row,col]    |
| Slice    | start:stop:step  |
| Boolean  | arr[arr > x]     |
| Fancy    | arr[[i,j]]       |
| Extra    | where, take, put |
