# **Phase 12 — Sorting and Searching**

# **1️⃣ `np.sort()` → Sorting Values**

What it does:

Returns a sorted copy of an array.

Syntax:

```np.sort(array, axis=-1)```

1️⃣ Example 1: 1D Array

In [1]:
import numpy as np

In [2]:
arr = np.array([5, 2, 9, 1, 7])
print(np.sort(arr))

[1 2 5 7 9]


| Original | Sorted |
| -------- | ------ |
| 5        | 1      |
| 2        | 2      |
| 9        | 5      |
| 1        | 7      |
| 7        | 9      |


2️⃣ Example 2: 2D Array

In [3]:
arr = np.array([[3, 1, 2],
                [9, 7, 8]])

print(np.sort(arr))        # sort rows
print(np.sort(arr, axis=0))  # sort columns

[[1 2 3]
 [7 8 9]]
[[3 1 2]
 [9 7 8]]


Row-wise (default):
| Row     | Sorted  |
| ------- | ------- |
| [3,1,2] | [1,2,3] |
| [9,7,8] | [7,8,9] |

Column-wise:
| Column        | Sorted |
| ------------- | ------ |
| [3,9]         |[3,9]   |
| [1,7]         |[1,7]   |
| [2,8]         |[2,8]   |


### **Important:**
- np.sort() → returns new array
- arr.sort() → sorts in-place

# **2️⃣ `np.argsort()` → Indices of Sorted Order**

What it does:

Returns the indices that would sort the array.

1️⃣ Example:

In [4]:
arr = np.array([50, 20, 40, 10])

print(np.argsort(arr))

[3 1 2 0]


| Value | Index |
| ----- | ----- |
| 10    | 3     |
| 20    | 1     |
| 40    | 2     |
| 50    | 0     |


In [5]:
sorted_arr = arr[np.argsort(arr)]
print(sorted_arr)

[10 20 40 50]


Same as `np.sort()`

2️⃣ Real Use Case

Sort one array based on another:

In [6]:
names = np.array(["Ali", "Sara", "John"])
scores = np.array([85, 95, 75])

order = np.argsort(scores)

print(names[order])
print(scores[order])

['John' 'Ali' 'Sara']
[75 85 95]


| Name | Score |
| ---- | ----- |
| John | 75    |
| Ali  | 85    |
| Sara | 95    |


# **3️⃣ `np.searchsorted()` → Find Insert Position**

What it does:

Finds the index where a value should be inserted to keep array sorted.

Important: Array must be sorted first

1️⃣ Example:

In [7]:
arr = np.array([10, 20, 30, 40])

print(np.searchsorted(arr, 25))

2


| Value | Position |
| ----- | -------- |
| 25    | 2        |


Because: `[10, 20, (25), 30, 40]`

2️⃣ Multiple Values:

In [8]:
print(np.searchsorted(arr, [5, 15, 35]))

[0 1 3]


| Value | Index |
| ----- | ----- |
| 5     | 0     |
| 15    | 1     |
| 35    | 3     |

Because: `[(5), 10, (15), 20, (25), 30, (35), 40]`

3️⃣ Left vs Right

In [9]:
arr = np.array([10, 20, 20, 20, 30])

print(np.searchsorted(arr, 20, side='left'))
print(np.searchsorted(arr, 20, side='right'))

1
4


| Side  | Index |
| ----- | ----- |
| left  | 1     |
| right | 4     |


### **Example**

In [10]:
# Top K smallest values
arr = np.array([9, 1, 5, 3, 7])

k = 3
indices = np.argsort(arr)[:k]
print(arr[indices])

[1 3 5]


# **Full Comparison Table**
| Function            | Purpose       | Returns      | Use Case                  |
| ------------------- | ------------- | ------------ | ------------------------- |
| `np.sort()`         | Sort values   | Sorted array | Clean data                |
| `np.argsort()`      | Sort indices  | Indices      | Ranking / mapping         |
| `np.searchsorted()` | Find position | Index        | Binary search / insertion |

# **When to Use What**

- Use sort → when you just need sorted values
- Use argsort → when working with labels + data
- Use searchsorted → when doing fast searching (binary search)

# **Summary (Short & Powerful)**
- sort → gives sorted values
- argsort → gives sorted indices
- searchsorted → gives insertion index