# **Phase 2 — Array Properties & Inspection**

**The Idea**

Every NumPy array has metadata (information about the array), not just values.

Think of it like this:

| Concept  | Meaning                         |
| -------- | ------------------------------- |
| Data     | The actual numbers              |
| Metadata | Shape, type, memory, dimensions |


# **1️⃣ Create One Base Array (we’ll use it for everything)**

In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],
               [4,5,6]], dtype=np.int32)
print(arr)

[[1 2 3]
 [4 5 6]]


# **2️⃣ Core Properties (Understand Structure)**

1️⃣ `.shape` → Structure of array

In [4]:
arr.shape

(2, 3)

| Rows | Columns |
| ---- | ------- |
| 2    | 3       |


2️⃣ `.ndim` → Number of dimensions

In [5]:
arr.ndim

2

| Array Type | ndim |
| ---------- | ---- |
| Scalar     | 0    |
| Vector     | 1    |
| Matrix     | 2    |
| Tensor     | 3+   |


3️⃣ `.size` → Total elements

In [8]:
arr.size

6

Formula:

`size = rows × columns`

# **3️⃣ Data Type & Memory**
1️⃣ `.dtype` → Type of data

In [9]:
arr.dtype

dtype('int32')

2️⃣ `.itemsize` → Size of ONE element (bytes)

In [10]:
arr.itemsize

4

| Type    | Bytes |
| ------- | ----- |
| int32   | 4     |
| float64 | 8     |


3️⃣ `.nbytes` → Total memory used

In [11]:
arr.nbytes

24

Formula:

`nbytes = size × itemsize`

# **4️⃣ Transform & View**

1️⃣ `.T` → Transpose (swap rows & columns)

In [12]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

| Before | After |
| ------ | ----- |
| (2,3)  | (3,2) |


2️⃣ `.flat` → Iterate over all elements

In [14]:
for i in arr.flat:
  print(i)

1
2
3
4
5
6


Converts array → 1D iterator

# **5️⃣ Complex Numbers Support**

1️⃣ `.real` and `.imag`

In [19]:
complex_arr = np.array([1+2j, 3+4j])

print(f"real part: {complex_arr.real}")
print(f"imaginary part: {complex_arr.imag}")

real part: [1. 3.]
imaginary part: [2. 4.]


| Property | Meaning        |
| -------- | -------------- |
| real     | real part      |
| imag     | imaginary part |


# **6️⃣ Change Data Type**

1️⃣ `.astype()` → Convert type

In [21]:
arr_float = arr.astype(float)
print(arr_float)

[[1. 2. 3.]
 [4. 5. 6.]]


***⚠️ Important Note***

`arr.astype(float)`

❌ does NOT modify original array

✔️ returns a new one

# **FULL COMBINED EXAMPLE (Covers EVERYTHING)**

In [22]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int32)

# Core Properties
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

# Data Type & Memory
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)
print("Total Bytes:", arr.nbytes)

# Transform & View
print("\nTranspose:\n", arr.T)
print("\nFlat iteration:")
for x in arr.flat:
    print(x, end=" ")

# Complex Numbers Support
complex_arr = np.array([1+2j, 3+4j])
print("\n\nReal:", complex_arr.real)
print("Imag:", complex_arr.imag)

# Change Data Type
print("\nConverted to float:\n", arr.astype(float))

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int32
Item Size: 4
Total Bytes: 24

Transpose:
 [[1 4]
 [2 5]
 [3 6]]

Flat iteration:
1 2 3 4 5 6 

Real: [1. 3.]
Imag: [2. 4.]

Converted to float:
 [[1. 2. 3.]
 [4. 5. 6.]]


# **Comparison Table**

| Property | What it tells you | Example Output |
| -------- | ----------------- | -------------- |
| shape    | structure         | (2,3)          |
| ndim     | dimensions        | 2              |
| size     | total elements    | 6              |
| dtype    | data type         | int32          |
| itemsize | bytes per element | 4              |
| nbytes   | total memory      | 24             |
| T        | transpose         | (3,2)          |
| flat     | iterator          | 1,2,3,4,5,6    |
| real     | real part         | [1.,3.]        |
| imag     | imaginary part    | [2.,4.]        |
| astype() | convert type      | float array    |


# **How to Read ANY Array Instantly (YOUR GOAL)**

When you see any array, think like this:

1. Shape? → structure

2. ndim? → complexity

3. dtype? → type of data

4. size? → how big

5. memory? → itemsize + nbytes

6. need transform? → use `.T`

7. need iteration? → use `.flat`

# **Mini Practice**
```
arr = np.arange(12).reshape(3,4)

# Print ALL properties
```
Your task:

- shape?
- ndim?
- size?
- nbytes?
- transpose shape?

In [34]:
arr = np.arange(12).reshape(3,4)

print(f"array:\n {arr}\n")

# Print ALL properties
print(f"Shape: {arr.shape}")
print(f"Dimensions: {arr.ndim}")
print(f"Size: {arr.size}")
print(f"Total memory: {arr.nbytes}")
print(f"Transpose:\n {arr.T}")

array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shape: (3, 4)
Dimensions: 2
Size: 12
Total memory: 96
Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# **Final Summary Table (Cheat Sheet)**

| Category  | Functions         |
| --------- | ----------------- |
| Structure | shape, ndim, size |
| Type      | dtype, astype()   |
| Memory    | itemsize, nbytes  |
| View      | T                 |
| Iteration | flat              |
| Complex   | real, imag        |
