# **Phase 10 — Performance & Advanced Topics (NumPy — PRO LEVEL)**

# **1️⃣ Vectorization vs Loops**

Definition
| Concept       | Meaning                                                        |
| ------------- | -------------------------------------------------------------- |
| Vectorization | Applying operations on entire arrays at once (no Python loops) |
| Loops         | Iterating element by element using Python `for`                |
---
⚡ Why Vectorization is Faster?

- NumPy uses C under the hood
- Avoids Python overhead
- Uses SIMD & optimized memory access


1️⃣ Example 1: Basic Addition

❌ Loop

In [1]:
import numpy as np

In [15]:
arr = np.arange(1, 6)
print(arr,"\n")

result = []

for x in arr:
    result.append(int(x + 5))

print(result)

[1 2 3 4 5] 

[6, 7, 8, 9, 10]


✅ Vectorized

In [3]:
arr = np.arange(1, 6)
result = arr + 5
print(result)

[ 6  7  8  9 10]



2️⃣ Example 2: Multiply Arrays

❌ Loop

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a,"\n")
print(b,"\n")
result = []

for i in range(len(a)):
    result.append(int(a[i] * b[i]))

print(result)

[1 2 3] 

[4 5 6] 

[4, 10, 18]


✅ Vectorized

In [9]:
result = a * b
print(result)

[ 4 10 18]


3️⃣ Example 3: Conditional Logic

❌ Loop

In [16]:
arr = np.array([1,2,3,4,5])
print(arr,"\n")

result = []

for x in arr:
    if x > 3:
        result.append(int(x))

print(result)

[1 2 3 4 5] 

[4, 5]


✅ Vectorized

In [17]:
result = arr[arr > 3]
print(result)

[4 5]


4️⃣ Example 4: Mathematical Functions

❌ Loop

In [18]:
import math
arr = np.array([1,4,9])
print(arr,"\n")

result = []
for x in arr:
    result.append(math.sqrt(x))
print(result)

[1 4 9] 

[1.0, 2.0, 3.0]


✅ Vectorized

In [19]:
result = np.sqrt(arr)
print(result)

[1. 2. 3.]


Comparison Table
| Feature         | Loops  | Vectorization |
| --------------- | ------ | ------------- |
| Speed           | Slow ❌ | Very Fast ✅   |
| Code Length     | Long ❌ | Short ✅       |
| Readability     | Medium | High          |
| Python Overhead | High ❌ | Low ✅         |


# **2️⃣ Memory Optimization**

Definition

Memory optimization = using **less RAM + efficient storage**


1️⃣ Example 1: Data Types


In [31]:
arr = np.array([1,2,3], dtype=np.int64)
print(arr.dtype)
print(arr.nbytes)

int64
24


Optimize:

In [30]:
arr = np.array([1,2,3], dtype=np.int8)
print(arr.dtype)
print(arr.nbytes)

int8
3


2️⃣ Example 2: Float Precision



In [29]:
arr = np.array([1.0, 2.0], dtype=np.float64)
print(arr.dtype)
print(arr.nbytes)

float64
16


Optimize:

In [28]:
arr = arr.astype(np.float32)
print(arr.dtype)
print(arr.nbytes)

float32
12


3️⃣ Example 3: Memory Size

In [33]:
arr = np.arange(1000)
print(arr.dtype)
print(arr.nbytes)

int64
8000


4️⃣ Example 4: Avoid Copies

In [34]:
a = np.arange(10)
b = a  # no new memory

# Verify they share the same memory
print(f"Are a and b the same object? {a is b}")

nAre a and b the same object? True


Data Type Comparison
| Type    | Bytes | Use Case       |
| ------- | ----- | -------------- |
| int8    | 1     | small integers |
| int32   | 4     | normal use     |
| int64   | 8     | large values   |
| float32 | 4     | ML models ✅    |
| float64 | 8     | high precision |


# **3️⃣ Copy vs View**

Definition
| Concept | Meaning                        |
| ------- | ------------------------------ |
| Copy    | New array (independent memory) |
| View    | Shares memory with original    |

1️⃣ Example 1: View


In [36]:
a = np.array([1,2,3])
b = a.view()

b[0] = 100
print(f"a array: \n{a}\n")  # changed!
print(f"b array: \n{b}\n")

a array: 
[100   2   3]

b array: 
[100   2   3]



2️⃣ Example 2: Copy

In [37]:
a = np.array([1,2,3])
b = a.copy()

b[0] = 100
print(f"a array: \n{a}\n")  # unchanged
print(f"b array: \n{b}\n")

a array: 
[1 2 3]

b array: 
[100   2   3]



3️⃣  Example 3: Slice = View


In [38]:
a = np.arange(10)
b = a[0:5]

b[0] = 99

print(f"a array: \n{a}\n")
print(f"b array: \n{b}\n")

a array: 
[99  1  2  3  4  5  6  7  8  9]

b array: 
[99  1  2  3  4]



4️⃣ Example 4: Force Copy

In [41]:
a = np.arange(10)
b = a[0:5].copy()

b[0] = 99

print(f"a array: \n{a}\n")
print(f"b array: \n{b}\n")

a array: 
[0 1 2 3 4 5 6 7 8 9]

b array: 
[99  1  2  3  4]



Comparison Table
| Feature         | Copy   | View   |
| --------------- | ------ | ------ |
| Memory          | New    | Shared |
| Speed           | Slower | Faster |
| Safe            | Yes    | No     |
| Reflect Changes | No     | Yes    |


# **4️⃣ Broadcasting**

Definition

Broadcasting = automatic expansion of arrays to match shapes

Rules:

1- Align shapes from right
2- Dimensions must be:
- Equal OR
- One of them is 1

1️⃣ Example 1: Scalar Broadcasting

In [44]:
arr = np.array([1,2,3])
result = arr + 5
print(result)

[6 7 8]


2️⃣ Example 2: 1D + 2D

In [45]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]]


3️⃣ Example 3: Column Broadcasting

In [46]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10],
              [20]])

print(a + b)

[[11 12 13]
 [24 25 26]]


4️⃣ Example 4: Mismatch Error

In [48]:
a = np.array([1,2,3])
b = np.array([1,2])

print(a + b)
# ERROR

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

5️⃣ Example 5: Fix Shape

In [49]:
a = np.array([1,2,3])
b = np.array([1,2,1])

print(a + b)

[2 4 4]


Broadcasting Table
| Shape A | Shape B | Result |
| ------- | ------- | ------ |
| (3,)    | scalar  | (3,)   |
| (2,3)   | (3,)    | (2,3)  |
| (2,3)   | (2,1)   | (2,3)  |

---

Broadcasting Compatibility Table

| Array A Shape | Array B Shape | Resulting Shape | Status | Logic |
| :--- | :--- | :--- | :--- | :--- |
| `(3, 4)` | `(3, 4)` | `(3, 4)` | **Match** | Dimensions are identical. |
| `(3, 4)` | `(4,)` | `(3, 4)` | **Match** | `(4,)` is treated as `(1, 4)`. The `1` stretches to `3`. |
| `(3, 1)` | `(3, 4)` | `(3, 4)` | **Match** | The `1` in Array A stretches to match the `4`. |
| `(3, 1)` | `(1, 4)` | `(3, 4)` | **Match** | Both stretch: A becomes `(3, 4)`, B becomes `(3, 4)`. |
| `(3, 4)` | `(3,)` | **Fail** | **Error** | Trailing dimensions `4` and `3` don't match and neither is `1`. |




# **5️⃣ Structured Arrays (Optional)**

Definition

Array with named fields (like database rows)

1️⃣ Example 1: Basic

In [50]:
# Define the structure
dtype = [('name', 'U10'), ('age', 'i4')]

# Create the array with data
arr = np.array([('Ali', 25), ('Omar', 30)], dtype=dtype)

print(arr['name'])

['Ali' 'Omar']


2️⃣ Example 2: Access Field

In [51]:
print(arr['age'])

[25 30]


Example 3: Filter

In [52]:
print(arr[arr['age'] > 26])

[('Omar', 30)]


Example 4: Multiple Types

In [53]:
# Define the structure
dtype = [('id', 'i4'), ('salary', 'f4')]

# Create the array with data
data = np.array([(101, 50000.50), (102, 62000.00), (103, 45500.75)], dtype=dtype)

print(f"Full Structured Array:\n{data}\n")

# Access by column name
print(f"All Salaries:\n{data['salary']}\n")

# Access a specific row
print(f"First Record: {data[0]}")

Full Structured Array:
[(101, 50000.5 ) (102, 62000.  ) (103, 45500.75)]

All Salaries:
[50000.5  62000.   45500.75]

First Record: (101, 50000.5)


Comparison
| Feature    | Structured Array | Normal Array |
| ---------- | ---------------- | ------------ |
| Data Types | Mixed            | Same         |
| Fields     | Named            | No           |
| Use Case   | Tabular          | Numeric      |
-----


# **NumPy Data Type Shorthand Codes**

| Code | Type | Description | Byte Size |
| :--- | :--- | :--- | :--- |
| `'b1'` | **Boolean** | True or False | 1 byte |
| `'i1'` | **Integer** | 8-bit signed integer | 1 byte |
| `'i2'` | **Integer** | 16-bit signed integer | 2 bytes |
| `'i4'` | **Integer** | 32-bit signed integer | 4 bytes |
| `'i8'` | **Integer** | 64-bit signed integer | 8 bytes |
| `'u4'` | **Unsigned Int** | 32-bit unsigned (positive only) | 4 bytes |
| `'f2'` | **Float** | Half-precision float | 2 bytes |
| `'f4'` | **Float** | Single-precision float | 4 bytes |
| `'f8'` | **Float** | Double-precision float | 8 bytes |
| `'c8'` | **Complex** | Complex number (two 32-bit floats) | 8 bytes |
| `'U10'` | **Unicode** | String of 10 Unicode characters | 40 bytes* |
| `'S10'` | **String** | Zero-terminated bytes (10 chars) | 10 bytes |
| `'M8'` | **Datetime** | 64-bit date/time | 8 bytes |

> **Note on Unicode:** In NumPy, `'U'` strings use 4 bytes per character to support the full Unicode range. So, `'U10'` actually reserves 40 bytes of memory per entry.

You can also specify how the bytes are ordered in memory by adding a prefix:
```
<i4: Little-endian (Standard for Intel/AMD processors)

>i4: Big-endian (Common in network protocols)
```


# **SUMMARY TABLE**
| Topic               | Key Idea                    | When to Use       |
| ------------------- | --------------------------- | ----------------- |
| Vectorization       | Replace loops               | Always for speed  |
| Memory Optimization | Reduce dtype size           | Large datasets    |
| Copy vs View        | Control memory sharing      | Avoid bugs        |
| Broadcasting        | Expand arrays automatically | Matrix ops        |
| Structured Arrays   | Named fields                | Tabular-like data |
---

# **FINAL TAKEAWAYS**

- ❗ Never use loops if NumPy can do it
- ❗ Always think about memory (dtype + copy)
- ❗ Broadcasting = hidden superpower
- ❗ Views can break your code silently
- ❗ Optimization matters in ML pipelines & big data