# **Phase 9 — Random & Statistics**

# **1️⃣ Random Basics**
What is Randomness?

Generating numbers that simulate uncertainty

Used in:

- ML model initialization
- Data sampling
- Simulations

Summary Table (Basics)

| Function | Meaning              | Range           |
| -------- | -------------------- | --------------- |
| rand     | Uniform distribution | [0, 1]          |
| randn    | Normal distribution  | mean=0, std=1   |
| randint  | Random integers      | [low, high]     |
| seed     | Fix randomness       | reproducibility |

1️⃣ `np.random.rand()`

Uniform distribution (equal probability)

In [2]:
import numpy as np

Example 1 (single value):

In [2]:
print(np.random.rand())

0.7833939151592293


Example 2 (1D array):

In [3]:
print(np.random.rand(5))

[0.56718895 0.79847261 0.43903392 0.75282045 0.26990026]


Example 3 (2D matrix):

In [4]:
print(np.random.rand(2,3))

[[0.24620674 0.96302653 0.35971313]
 [0.21112573 0.16708483 0.4162836 ]]


Example 4 (compare multiple runs):

In [5]:
print(np.random.rand(3),"\n")
print(np.random.rand(3),"\n")

[0.82497555 0.92211885 0.40367486] 

[0.16536252 0.27851081 0.65205213] 



Different results each time

2️⃣ np.random.randn()

- Normal (Gaussian) distribution
- Mean = 0, Std = 1

Example 1:

In [6]:
print(np.random.randn())

0.3412131169557211


Example 2:

In [7]:
print(np.random.randn(5))

[-0.8450952  -0.91143413  0.90403912 -0.57720898  1.07594456]


Example 3 (2D):

In [8]:
print(np.random.randn(2,3))

[[-1.14918105  0.35191374 -1.39422156]
 [ 0.66675356 -0.04569511  0.59039403]]


Example 4 (scaled distribution):

In [10]:
# Generates 1,000 random numbers following a Normal Distribution
# with a Mean (average) of 50 and a Standard Deviation of 10.
A = np.random.randn(1000) * 10 + 50
print(A)

[44.08594094 42.92250177 42.82456378 31.35587529 53.39142348 51.71388489
 44.68423655 44.8524817  43.70341414 45.71949751 55.57657693 45.59922413
 40.45696263 49.78900103 41.72260175 56.24575159 67.09777336 65.82362073
 50.01132996 53.77624565 52.30606962 57.91522456 50.54594721 60.94863583
 57.49105861 30.85228145 58.63500194 46.20725014 56.71081491 43.27827438
 57.92205761 53.75488719 38.97163291 46.94391323 72.47107104 68.59909047
 56.19149546 55.20819266 52.69600352 55.92521363 47.77378999 43.1833256
 64.54391084 52.99281902 59.95581827 49.99842225 36.44912929 50.05773042
 46.23798815 60.37052763 42.0128339  42.71818566 39.08909363 36.11666609
 59.0277177  39.97060547 55.37013005 58.67916079 66.37039394 30.74251469
 50.61857664 69.09405072 30.25732467 51.37598151 52.94652252 54.59451211
 43.04479286 54.71215946 65.19513604 50.25742678 59.81506483 41.10829891
 53.2201565  56.31959109 35.34724086 49.10438035 47.15212263 47.02160045
 40.39986519 42.55789895 50.86076958 50.5345438  44.

$$X = \sigma Z + \mu$$

- $X$: The resulting General Normal Distribution (your variable A).
- $Z$: The Standard Normal Distribution (`the np.random.randn()` part).
- $\sigma$ (Sigma): The Standard Deviation (the 10).
- $\mu$ (Mu): The Mean (the 50).

---
Summary Table
| Component | Math Term | Effect on Data |
| :--- | :--- | :--- |
| **`randn(1000)`** | Distribution | Creates 1,000 points centered at $0$ |
| **`* 10`** | $\sigma$ (Sigma) | Stretches the curve (makes it wider) |
| **`+ 50`** | $\mu$ (Mu) | Moves the center of the curve to $50$ |
------

Why do this?

If you are building a machine learning model to predict house prices or student grades, you often need "fake" data that looks "real." Real-world data is almost always "Normal" (most values are near the average, with few extremes), and this formula is the quickest way to create it.

3️⃣ `np.random.randint()`
Random integers

Example 1:

In [3]:
print(np.random.randint(0,10))

6


Example 2:

In [4]:
print(np.random.randint(1,100, size=5))

[ 5 64 49 72  2]


Example 3 (matrix):

In [6]:
print(np.random.randint(10,20, size=(2,3)))

[[13 16 10]
 [14 15 18]]


Example 4 (negative range):

In [7]:
print(np.random.randint(-5,5, size=4))

[-5  4 -3 -1]


4️⃣ `np.random.seed()`

Fix randomness

Example 1:

In [8]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


Run again → SAME result

Example 2:

In [9]:
np.random.seed(1)
print(np.random.randint(0,10,5))

np.random.seed(1)
print(np.random.randint(0,10,5))

[5 8 9 5 0]
[5 8 9 5 0]


identical outputs

Example 3 (ML use):

In [10]:
np.random.seed(0)
weights = np.random.randn(3,3)
print(weights)

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]


# **2️⃣ Specific Distributions**

Summary Table
| Function | Distribution    | Use Case          |
| -------- | --------------- | ----------------- |
| choice   | Sampling        | dataset selection |
| binomial | Success/failure | classification    |
| poisson  | Event counts    | time-based events |



1️⃣ np.random.choice()

Important Rule ⚠️

Pick random values from array

Example 1:

In [11]:
arr = [10, 20, 30, 40]
print(np.random.choice(arr))

30


Example 2 (multiple picks):

In [12]:
print(np.random.choice(arr, size=3))

[40 40 30]


Example 3 (with probability):

In [13]:
print(np.random.choice(arr, size=5, p=[0.1,0.2,0.3,0.4]))

[30 40 10 10 10]


`p=[0.1, 0.2, 0.3, 0.4]`: The specific probability for each item in arr.

- The 1st item has a 10% chance.

- The 2nd item has a 20% chance.

- The 3rd item has a 30% chance.

- The 4th item has a 40% chance (The "luckiest" item).

Example 4 (without replacement):

In [14]:
print(np.random.choice(arr, size=3, replace=False))

[30 10 20]


`replace=False` (Unique Sampling)
This is like picking a marble out of a bag and keeping it in your pocket.

- Every item picked is unique.

- Once an item is chosen, it is removed from the "pool" for the next draw.

2️⃣ `np.random.binomial()`

Binary outcomes (success/failure)

Parameters:
- n = number of trials
- p = probability of success

binomial math formula:

$$\binom{n}{k} = \frac{n!}{k!(n-k)!}$$

formula for the probability of $k$ successes:

$$P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}$$

Summary Table

| Symbol | Name | Referent / Meaning |
| :--- | :--- | :--- |
| **$n$** | Trials | How many times did you try? |
| **$k$** | Successes | How many "wins" are you looking for? |
| **$p$** | Success Probability | How likely is a "win" in one try? |
| **$1-p$ ($q$)** | Failure Probability | How likely is a "loss" in one try? |
| **$\binom{n}{k}$** | Combinations | How many patterns of wins/losses exist? |

----

Example in Words:

If you are shooting **10 basketball free throws** ($n=10$) and your skill level is **70%** ($p=0.7$), what is the chance you make **exactly 8** ($k=8$)?

1.  $\binom{10}{8}$ counts the different sequences of makes/misses that result in 8 total makes.
2.  $0.7^8$ is the probability of the 8 makes.
3.  $0.3^2$ is the probability of the 2 misses.

-------
Example 1:

In [15]:
print(np.random.binomial(10, 0.5))

3


Example 2:

In [16]:
print(np.random.binomial(10, 0.2, size=5))

[3 2 3 2 3]


Example 3 (extreme probability):

In [17]:
print(np.random.binomial(10, 0.9, size=5))

[ 9  9  9  8 10]


Example 4 (coin flip simulation):

In [18]:
print(np.random.binomial(1, 0.5, size=10))

[0 0 1 0 0 0 0 0 0 1]


3️⃣ `np.random.poisson()`

counts events in fixed interval

The Mathematical Formula:

$$P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!}$$

Summary Table

| Symbol | Name | Plain English Meaning |
| :--- | :--- | :--- |
| **$\lambda$** | Rate Parameter | "On average, how many usually happen?" |
| **$k$** | Occurrences | "How many am I betting will happen now?" |
| **$e^{-\lambda}$** | Decay Factor | Adjusts the probability based on the average rate. |
| **$k!$** | Factorial | Normalizes the probability as $k$ increases. |


Example 1:

In [22]:
# 3: The average number of events (lambda) expected per interval.
print(np.random.poisson(3))

3


Example 2:

In [20]:
print(np.random.poisson(5, size=10))

[6 6 7 2 6 8 6 6 4 9]


Example 3 (rare events):

In [21]:
print(np.random.poisson(0.5, size=10))

[1 1 0 1 1 0 0 1 0 1]


Example 4 (large rate):

In [23]:
print(np.random.poisson(20, size=10))

[13 21 33 16 17 19 18 15 26 14]


# **3️⃣ Statistical Aggregates**

Summary Table

| Function   | Meaning               |
| ---------- | --------------------- |
| mean       | average               |
| median     | middle value          |
| std        | spread                |
| var        | variance              |
| percentile | distribution position |

1️⃣ `np.mean()`

Example 1:

In [24]:
arr = [1,2,3,4]
print(np.mean(arr))

2.5


Example 2:

In [25]:
print(np.mean([[1,2],[3,4]]))

2.5


Example 3 (axis):

In [27]:
A = np.array([[1,2],
              [3,4]])

print(np.mean(A, axis=0),"\n")
print(np.mean(A, axis=1),"\n")

[2. 3.] 

[1.5 3.5] 



2️⃣ `np.median()`

The median is the value separating the higher half from the lower half of a data sample.

- 50% of the numbers are greater than or equal to the median.

- 50% of the numbers are less than or equal to the median.

Example 1:

In [28]:
print(np.median([1,2,3,100]))

2.5


Robust to outliers

Example 2:

In [29]:
print(np.median([[1,5],[2,10]]))

3.5


Example 3:

In [30]:
A = np.array([[1,2],
              [3,4]])

print(np.median(A, axis=0))

[2. 3.]


3️⃣ `np.std()` (Standard Deviation)

Measures spread

Standard Deviation represents the "average distance" of every data point from the center of the data. It is the square root of the Variance.

The Mathematical Formula:

$$\sigma = \sqrt{\frac{\sum_{i=1}^{n} (x_i - \mu)^2}{n}}$$


- $\sigma$ (Sigma): The Standard Deviation.
- $x_i$: Each individual value in your data.
- $\mu$ (Mu): The Mean (average) of all the data points.
- $n$: The total number of values in the dataset.
- $\sum$: The Greek symbol for "Sum" (add everything up).

Example 1:


In [31]:
print(np.std([1,2,3,4]))

1.118033988749895


Example 2:

In [32]:
A = np.array([[1,2],
              [3,4]])

np.std(A, axis=0)

array([1., 1.])

Example 3 (compare spread):

In [33]:
# Explanation: Every number is the same.
# There is NO "deviation" from the average (10).
# The data is 100% consistent.
print(np.std([10,10,10]),"\n")

# Explanation: The numbers are very far apart (1 to 100).
# The average is 37.0, but the points are nowhere near it.
# This indicates high "volatility" or a wide spread.
print(np.std([1,10,100]),"\n")

0.0 

44.69899327725402 



4️⃣ `np.var()` (Variance): Square of std

Variance measures how far a set of numbers is spread out from their average value.

- If Variance = 0, all values are identical.

- A small variance indicates that the data points tend to be very close to the mean.

- A high variance indicates that the data points are very spread out from the mean and from each other.

The Mathematical Formula

$$\sigma^2 = \frac{\sum_{i=1}^{n} (x_i - \mu)^2}{n}$$

- $\sigma^2$: The symbol for Variance (pronounced "Sigma squared").
- $\sum$: The sum of all elements.
- $x_i$: Each individual data point.
- $\mu$: The Mean (average) of the data.
- $n$: The total number of data points.



Example 1:


In [35]:
print(np.var([1,2,3,4]))

1.25


Example 2:

In [37]:
A = np.array([[1,2],
              [3,4]])

print(np.var(A, axis=1))

[0.25 0.25]


5️⃣ `np.percentile()`: Position in distribution

The $P$-th percentile is the value such that $P\%$ of the data is less than or equal to that value.
- 25th Percentile ($Q1$): 25% of data is below this point.
- 50th Percentile ($Q2$): 50% of data is below this point (This is the Median).
- 75th Percentile ($Q3$): 75% of data is below this point.

The Mathematical Formula

$$R = \frac{P}{100} \times (n - 1)$$

The Interpolation Formula:
$$\text{Percentile Value} = V_{low} + (V_{high} - V_{low}) \times \text{fraction}$$


Example 1:



In [38]:
print(np.percentile([1,2,3,4,5], 50))

3.0


median


The 50th percentile is the "cut-off" point where 50% of the data lies below it and 50% lies above it. It represents the exact middle of your dataset.

Example 2:

In [39]:
print(np.percentile([1,2,3,4,5], 25),"\n")
print(np.percentile([1,2,3,4,5], 75),"\n")

2.0 

4.0 



Example 3 (multiple percentiles):

In [40]:
print(np.percentile([1,2,3,4,5], [25,50,75]))

[2. 3. 4.]


Example 4 (axis):

In [41]:
A = np.array([[1,2],
              [3,4]])

print(np.percentile(A, 50, axis=0))

[2. 3.]


# **COMPARISON TABLE**
| Concept | Sensitive to Outliers? | Use             |
| ------- | ---------------------- | --------------- |
| Mean    | ✅ Yes                  | general average |
| Median  | ❌ No                   | skewed data     |
| Std     | ✅ Yes                  | spread          |
| Var     | ✅ Yes                  | math operations |
--------------
# **SUMMARY**
| Category     | Function   | Purpose         |
| ------------ | ---------- | --------------- |
| Random       | rand       | uniform         |
| Random       | randn      | normal          |
| Random       | randint    | integers        |
| Control      | seed       | reproducibility |
| Sampling     | choice     | select data     |
| Distribution | binomial   | success/failure |
| Distribution | poisson    | event counts    |
| Stats        | mean       | average         |
| Stats        | median     | center          |
| Stats        | std        | spread          |
| Stats        | var        | variance        |
| Stats        | percentile | ranking         |

# **MOST IMPORTANT FOR ML:**

- `randn()` → weight initialization
- `seed()` → reproducibility
- `mean`, `std` → normalization
- `choice()` → sampling datasets
- `binomial` → classification problems
- `percentile` → outlier detection