# **Phase 6 — Reshaping & Manipulation**

The Idea

You are not changing the data, You are changing how the data is viewed/structured

Base Arrays

In [1]:
import numpy as np

arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# **1️⃣ `reshape()`**

Idea

Change shape WITHOUT changing data

1️⃣ Basic Examples

In [2]:
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2️⃣ 3D Example

In [4]:
print(arr.reshape(2,2,3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3️⃣ Auto dimension (`-1`)

In [5]:
print(arr.reshape(3, -1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


shape = (3,4)

In [6]:
print(arr.reshape(-1, 2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


shape = (6,2)

NumPy calculates automatically

4️⃣ Invalid reshape ❌

In [7]:
print(arr.reshape(5,3))

ValueError: cannot reshape array of size 12 into shape (5,3)

ERROR → total elements must match

**reshape RULE TABLE**

| Rule                  | Meaning      |
| --------------------- | ------------ |
| Total elements same   | MUST         |
| Order preserved       | YES          |
| -1 allowed            | Auto compute |
| Can go to higher dims | YES          |


# **2️⃣ 2. flatten() — Convert to 1D (COPY)**

Concept

- Always returns a copy
- Original array NOT affected

1️⃣ EXAMPLES

In [28]:
a = np.array([[1,2], [3,4]])
print(f"before flatten: \n{a}\n")

b = a.flatten()

print(f"after flatten: {b}")

before flatten: 
[[1 2]
 [3 4]]

after flatten: [1 2 3 4]


In [20]:
arr2 = arr.reshape(3,4)
print(f"before flatten: \n{arr2}\n")

flat = arr2.flatten()
print(f"before flatten: \n{flat}\n")

before flatten: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

before flatten: 
[ 1  2  3  4  5  6  7  8  9 10 11 12]



2️⃣ Modify result

In [29]:
b[0] = 100
print(f"a array before modify: \n {a}\n")
print(f"b array before modify: {b}")

a array before modify: 
 [[1 2]
 [3 4]]

b array before modify: [100   2   3   4]


⚠️ DOES NOT change original array

# **3️⃣ ravel() — Convert to 1D (VIEW)**

Concept

- Returns view if possible
- Changes affect original array

1️⃣ EXAMPLES

In [30]:
a = np.array([[1, 2], [3, 4]])
print(f"before ravel: \n{a}\n")

b = a.ravel()
print(f"before ravel: \n{b}\n")

before ravel: 
[[1 2]
 [3 4]]

before ravel: 
[1 2 3 4]



In [25]:
arr2 = arr.reshape(3,4)
print(f"before ravel: \n{arr2}\n")

ravel = arr2.ravel()
print(f"before ravel: \n{ravel}\n")

before ravel: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

before ravel: 
[ 1  2  3  4  5  6  7  8  9 10 11 12]



2️⃣ Modify result

In [34]:
b[0] = 100
print(f"a array before modify: \n {a}\n")
print(f"b array before modify: \n {b}")

a array before modify: 
 [[100   2]
 [  3   4]]

b array before modify: 
 [100   2   3   4]


⚠️ CHANGES original array❗

Table

| Function | Memory | Effect            |
| -------- | ------ | ----------------- |
| flatten  | copy   | safe              |
| ravel    | view   | modifies original |


# **4️⃣ transpose() / `.T`**

Concept

- Convert rows → columns

1️⃣ 2D Example



In [36]:
arr2 = arr.reshape(3,4)
print(f"arr2 before transpose:\n{arr2}\n")

print(f"arr2 after transpose:\n{arr2.T}")

arr2 before transpose:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr2 after transpose:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Shape becomes (4,3)

More Examples

In [37]:
print(np.transpose(arr2))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Same result

2️⃣ 3D Transpose

In [39]:
x = np.arange(8).reshape(2,2,2)
print(f"x before transpose:\n{x}\n")

print(f"x after transpose:\n{np.transpose(x, (1,0,2))}\n")

x before transpose:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

x after transpose:
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]



swaps axes

In [42]:
a = np.arange(8).reshape(2,2,2)
print(f"a before transpose:\n{a}\n")

b = a.transpose(1,0,2)
print(f"b after transpose:\n{b}\n")

a before transpose:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

b after transpose:
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]



Same result

**transpose RULE**

| Input Shape | Output Shape    |
| ----------- | --------------- |
| (2, 3)      | (3, 2)          |
| (a, b, c)   | depends on axes |


**Table**
| Function    | Meaning           |
| ----------- | ----------------- |
| .T          | swap rows/columns |
| transpose() | full control      |


# **5️⃣ Resize (VERY IMPORTANT ⚠️)**
Two types:

1️⃣ `np.resize()` (function)

Can repeat data

In [43]:
a = np.array([1,2,3])
print(f"b before resize:\n{a}\n")

b = np.resize(a, (2,4))
print(f"b after resize:\n{b}\n")

b before resize:
[1 2 3]

b after resize:
[[1 2 3 1]
 [2 3 1 2]]



2️⃣ `a.resize()` (method)

Expanding


In [50]:
arr = np.array([1,2,3,4])
print(f"arr before resize:\n{arr}\n")

arr.resize(3,3)
print(f"arr after resize:\n{arr}\n")

arr.resize(3,3,3)
print(f"arr after second resize:\n{arr}\n")

arr before resize:
[1 2 3 4]

arr after resize:
[[1 2 3]
 [4 0 0]
 [0 0 0]]

arr after second resize:
[[[1 2 3]
  [4 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]



**⚠️ fills with 0**

**⚠️ Important**

- modifies original array
- dangerous if not careful

**resize vs reshape**

| Feature      | reshape | resize |
| ------------ | ------- | ------ |
| Safe         | ✅       | ❌      |
| Changes data | ❌       | ✅      |
| Repeats data | ❌       | ✅      |


# **5️⃣ Axis Control**

Concept

Axis = direction

In [51]:
a = np.array([[1,2,3],
              [4,5,6]])

    # Axis 0 (columns ↓)
print(np.sum(a, axis=0))
    # Axis 1 (rows →)
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


**Axis Table**
| Axis | Meaning        |
| ---- | -------------- |
| 0    | Down (columns) |
| 1    | Across (rows)  |


1️⃣ Add dimension

In [73]:
arr = np.arange(1,7).reshape(2,3)
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [74]:
a = arr[np.newaxis, :]
print(a.shape)

(1, 2, 3)


shape: (1,2,3)

In [75]:
a = arr[:, np.newaxis]
print(a.shape)

(2, 1, 3)


shape: (2,1,3)

2️⃣ expand_dims()

In [76]:
a = np.expand_dims(arr, axis=0) # add new axis at row
print(a.shape)

(1, 2, 3)


In [77]:
a = np.expand_dims(arr, axis=1) # add new axis at column
print(a.shape)

(2, 1, 3)


3️⃣ Remove dimension

In [81]:
x = np.array([[[1,2,3]]])
print(x.shape)
a = np.squeeze(x)
print(a.shape)

(1, 1, 3)
(3,)


removes extra dimensions

**Table**

| Function    | Purpose    |
| ----------- | ---------- |
| newaxis     | add dim    |
| expand_dims | add dim    |
| squeeze     | remove dim |


# **6️⃣ Shape Control (Pro Level)**

1️⃣ `reshape` for ML

In [70]:
X = np.array([1,2,3,4])
print(X, "\n")
print(X.reshape(-1,1),"\n")   # column vector
print(X.reshape(1,-1), "\n")   # row vector

[1 2 3 4] 

[[1]
 [2]
 [3]
 [4]] 

[[1 2 3 4]] 



**Why important?**

| Shape | Meaning |
| ----- | ------- |
| (n,)  | 1D      |
| (n,1) | column  |
| (1,n) | row     |


# **FULL COMBINED EXAMPLE**

In [71]:
arr = np.arange(1,13)

# reshape
x = arr.reshape(3,4)

# flatten vs ravel
flat = x.flatten()
rav = x.ravel()

# transpose
t = x.T

# expand dims
new = x[np.newaxis, :]

# squeeze
sq = np.squeeze(new)

print(f"reshape: \n{x}\n")
print(f"flat: \n{flat}\n")
print(f"ravel: \n{rav}\n")
print(f"transpose: \n{t}\n")
print(f"expand dims: \n{new.shape}\n")
print(f"squeeze: \n{sq.shape}\n")

reshape: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

flat: 
[ 1  2  3  4  5  6  7  8  9 10 11 12]

ravel: 
[ 1  2  3  4  5  6  7  8  9 10 11 12]

transpose: 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

expand dims: 
(1, 3, 4)

squeeze: 
(3, 4)



# **COMPARISON TABLE (VERY IMPORTANT)**
| Concept   | Function        |
| --------- | --------------- |
| reshape   | change shape    |
| flatten   | copy → 1D       |
| ravel     | view → 1D       |
| transpose | swap axes       |
| resize    | change original |
| newaxis   | add dim         |
| squeeze   | remove dim      |

# **FINAL SUMMARY TABLE**
| Topic       | Function  | Key Idea     |
| ----------- | --------- | ------------ |
| Reshape     | reshape() | change shape |
| Flatten     | flatten() | copy 1D      |
| Ravel       | ravel()   | view 1D      |
| Transpose   | .T        | swap axes    |
| Resize      | resize()  | change size  |
| Axis        | axis=0/1  | direction    |
| Dim control | newaxis   | add dim      |

# **HOW TO THINK**
| Goal             | Use       |
| ---------------- | --------- |
| change structure | reshape   |
| flatten safely   | flatten   |
| flatten fast     | ravel     |
| rotate matrix    | transpose |
| add dimension    | newaxis   |
| remove dimension | squeeze   |


# **Practice**
```
arr = np.arange(1,25)

# 1. reshape to (4,6)
# 2. reshape to (2,3,4)
# 3. flatten it
# 4. use ravel and modify first element
# 5. transpose a (3,4) array
# 6. convert [1,2,3,4] to column vector
```



In [84]:
arr = np.arange(1,25)

# 1. reshape to (4,6)
a = arr.reshape(4,6)
print(f"reshape arr(a):\n {a}\n")

# 2. reshape to (2,3,4)
b = arr.reshape(2,3,4)
print(f"reshape arr(b):\n {b}\n")

# 3. flatten it
flat_a = a.flatten()
flat_b = b.flatten()
print(f"flat_a: \n{flat_a}\n")
print(f"flat_b: \n{flat_b}\n")

# 4. use ravel and modify first element
ravel_a = a.ravel()
ravel_a[0] = 99
print(f"ravel_a: \n{ravel_a}\n")
ravel_b = b.ravel()
ravel_b[0] = 999
print(f"ravel_b: \n{ravel_b}\n")

# 5. transpose a (3,4) array
arr1 = np.arange(1,13).reshape(3,4)
print(f"transpose: \n{arr1.T}\n")

# 6. convert [1,2,3,4] to column vector
X = np.array([1,2,3,4])
print(f"X array before convert: \n{X}\n")
a = X.reshape(-1,1)
print(f"column vector: \n{a}\n")

reshape arr(a):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

reshape arr(b):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

flat_a: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

flat_b: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

ravel_a: 
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

ravel_b: 
[999   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24]

transpose: 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

X array before convert: 
[1 2 3 4]

column vector: 
[[1]
 [2]
 [3]
 [4]]



# **FINAL CHEAT SHEET**

| Category    | Tools                |
| ----------- | -------------------- |
| Shape       | reshape              |
| Flatten     | flatten, ravel       |
| Rotation    | transpose            |
| Resize      | resize               |
| Dim Control | newaxis, expand_dims |
| Dim Reduce  | squeeze              |
