# **Phase 8 — Linear Algebra**

The Idea

You are combining and breaking arrays
| Action    | Meaning        |
| --------- | -------------- |
| Stacking  | combine arrays |
| Splitting | divide arrays  |


Base Arrays

# **1️⃣ Matrix Basics**

Definitions
| Concept   | What it does               |
| --------- | -------------------------- |
| Transpose | Flip rows ↔ columns        |
| Identity  | Matrix with 1s on diagonal |
| Diagonal  | Extract or create diagonal |


1️⃣ Transpose

Converts rows → columns

Examples:

In [1]:
import numpy as np

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


Example 2 (square matrix):

In [5]:
B = np.array([[1, 2],
              [3, 4]])

print(np.transpose(B))

[[1 3]
 [2 4]]


2️⃣ Identity Matrix

In [6]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Used in ML: initialization, linear transformations

3️⃣ Diagonal

Extract diagonal:

In [8]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.diag(A))

[1 5 9]


Create diagonal

In [9]:
print(np.diag([1, 2, 3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# **2️⃣ Core Operations**

Summary
| Operation   | Meaning               |
| ----------- | --------------------- |
| Dot product | Multiply & sum        |
| @           | Matrix multiplication |


1️⃣ Dot Product

Important Rule ⚠️

`(cols of A) == (rows of B)`

1D vectors:

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


Result = `1*4 + 2*5 + 3*6 = 32`

2D matrices:

In [11]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

np.dot(A,B)

array([[19, 22],
       [43, 50]])

- `first element(0,0) = (1*5)+(2*7)=5+14=19`
- `second element(0,1) = (1*6)+(2*8)=6+16=22`
- `third element(1,0) = (3*5)+(4*7)=15+28=43`
- `forth elememnt(1,1) = (3*6)+(4*8)=18+32=50`



2️⃣ Matrix Multiplication (@)

In [12]:
A @ B

array([[19, 22],
       [43, 50]])

Same as np.dot(A,B) but cleaner



# **3️⃣ Matrix Properties**

Summary Table

| Property    | Meaning                  |
| ----------- | ------------------------ |
| Determinant | Scaling factor           |
| Rank        | Independent rows/columns |
| Trace       | Sum of diagonal          |


1️⃣ Determinant

the determinant gives you a scalar that tells you if the matrix can be inverted and how it transforms space.

A =$\begin{bmatrix} a & b \\ c & d \end{bmatrix}$

`det (A)=ad-bc`

- If det ≠ 0, the matrix is invertible.
- If det = 0, the matrix is singular (not invertible).
- Positive/negative values indicate orientation (preserve vs. flip).





In [13]:
A = np.array([[1,2],
              [3,4]])

np.linalg.det(A)

np.float64(-2.0000000000000004)

`det (A)=(1*4)-(2*3)=-2`



2️⃣ Rank

gives the number of independent rows/columns in A


In [15]:
A = np.array([[1,2],
              [2,4]])

print(np.linalg.matrix_rank(A))

1


Rank = 1 (dependent rows)

3️⃣ Trace

Sum diagonal: `1+4 = 5`

In [16]:
print(np.trace(A))

5


# **4️⃣ Matrix Transformations**

Summary

| Operation | Meaning                 |
| --------- | ----------------------- |
| Inverse   | Undo transformation     |
| Power     | Repeated multiplication |


1️⃣ Inverse

The inverse of a square matrix A is another matrix $\ A^{-1}$ such that:

$A \cdot A^{-1} = I$

| Term | Meaning | Analogy in Numbers |
| :--- | :--- | :--- |
| **$A$** | The original square matrix | $x$ |
| **$A^{-1}$** | The inverse matrix | $\frac{1}{x}$ |
| **$I$** | The Identity matrix (diagonal of $1$s) | $1$ |

where I is the identity matrix.
- If the determinant of A is not zero, the inverse exists.
- If the determinant is zero, the matrix is singular and has no inverse.

- `np.linalg.inv(A)` computes the inverse of matrix A.
- `A @ np.linalg.inv(A)` means multiply A by its inverse($A \cdot A^{-1} = I$).




In [18]:
A = np.array([[1,2],
              [3,4]])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


Check:

In [19]:
print(A @ np.linalg.inv(A))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


Identity matrix

`np.linalg.inv(A)` gives the inverse, while `A @ np.linalg.inv(A)` checks that multiplying them returns the identity matrix.


# **5️⃣ Solving Systems**

Problem:
`Ax = b`

In [22]:
A = np.array([[2,1],
              [1,3]])

b = np.array([8,13])

x = np.linalg.solve(A,b)
print(x)

[2.2 3.6]


The Mathematical RepresentationThe code provided represents the following system of equations:$$\begin{cases}
2x_1 + 1x_2 = 8 \\
1x_1 + 3x_2 = 13
\end{cases}$$In matrix form, this is written as:$$\begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} 8 \\ 13 \end{bmatrix}$$

---
`np.linalg.solve(A, b)`:
$$x = A^{-1} \cdot b$$

$x_1 = 2.2 \\ x_2=3.6$

$ Equation 1: 2(2.2) + 1(3.6) = 4.4 + 3.6 = 8$

$Equation 2: 1(2.2) + 3(3.6) = 2.2 + 10.8 = 13$

Example 2 (3 variables):


In [25]:
A = np.array([[1,1,1],
              [2,3,1],
              [1,-1,2]])

b = np.array([6,10,5])

print(np.linalg.solve(A,b))

[-2.  3.  5.]


The Mathematical Representation:
$$\begin{cases}
1x_1 + 1x_2 + 1x_3 = 6 \\
2x_1 + 3x_2 + 1x_3 = 10 \\
1x_1 - 1x_2 + 2x_3 = 5
\end{cases}$$

In matrix notation ($Ax = b$), this is expressed as:
$$\begin{bmatrix} 1 & 1 & 1 \\ 2 & 3 & 1 \\ 1 & -1 & 2 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = \begin{bmatrix} 6 \\ 10 \\ 5 \end{bmatrix}$$

-----

👉 Used heavily in:

- Linear Regression
- Optimization
- Neural Networks

# **6️⃣ Vector Operations**

1️⃣ Norms

Definition:

Measure vector length

$\| v\| =\sqrt{x^2+y^2}$




In [26]:
v = np.array([3,4])
print(np.linalg.norm(v))

5.0


Step-by-step math:

$\| v\| =\sqrt{3^2+4^2}=\sqrt{9+16}=\sqrt{25}=5$

`np.linalg.norm(v)` computes the length of the vector using the Pythagorean theorem.





In [27]:
print(np.linalg.norm(v, ord=1))  # Manhattan
print(np.linalg.norm(v, ord=2))  # Euclidean
print(np.linalg.norm(v, ord=np.inf))  # Max

7.0
5.0
4.0


1. Manhattan Norm (L1 norm, `ord=1`)

This is the sum of absolute values:

$\| v\| _1=|3|+|4|=3+4=7$

2. Euclidean Norm (L2 norm, `ord=2`)

This is the standard length (Pythagorean theorem):

$\| v\| _2=\sqrt{3^2+4^2}=\sqrt{9+16}=\sqrt{25}=5$

3. Maximum Norm (Infinity norm, `ord=\infty`)

This is the maximum absolute value:

$\| v\| _{\infty }=\max (|3|,|4|)=\max (3,4)=4$




Why do we need different norms?

In Machine Learning, we use these for Regularization:

- $L^1$ (Manhattan) is used when you want a "sparse" model (it likes to push unimportant weights to exactly zero).
- $L^2$ (Euclidean) is used to keep weights small but non-zero, preventing any single feature from dominating the model.

Summary

| Norm | Meaning   |
| ---- | --------- |
| Manhattan(L1)   | Sum abs   |
| Euclidean(L2)   | Distance  |
| Max(Inf)  | Max value |


# **7️⃣ Decompositions**

1️⃣ Eigen Decomposition

Concept:

$ Av=λv $

- $A$: Your transformation matrix.

- $\mathbf{v}$: The Eigenvector (a non-zero vector).
- $\lambda$: The Eigenvalue (a scalar/number that scales the vector).

Matrix stretches vector

In [30]:
A = np.array([[2,0],
              [0,3]])

values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[2. 3.]
[[1. 0.]
 [0. 1.]]


8️⃣ SVD
Concept:

$ A=UΣV^T $

- $U$: Left Singular Vectors (Rotates the space).

- $\Sigma$ (or $S$): Singular Values (Scales/stretches the space).

- $V^T$: Right Singular Vectors (Rotates the space back or to a new orientation).

In [36]:
A = np.array([[1,2],
              [3,4]])

U, S, Vt = np.linalg.svd(A)
print(U,"\n")
print(S,"\n")
print(Vt,"\n")

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] 

[5.4649857  0.36596619] 

[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]] 



Used in:

- PCA
- Image compression
- Recommender systems

9️⃣ QR Decomposition

A = Q × R

- Q → orthogonal
- R → upper triangular

In [42]:
Q, R = np.linalg.qr(A)
print(Q,"\n")
print(Q,"\n")

[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]] 

[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]] 



# **SUMMARY**
| Category   | Function                  | Use            |
| ---------- | ------------------------- | -------------- |
| Basics     | `.T`, `np.eye`, `np.diag` | Structure      |
| Core Ops   | `dot`, `@`                | Multiply       |
| Properties | `det`, `rank`, `trace`    | Analyze        |
| Transform  | `inv`, `matrix_power`     | Transform      |
| Solve      | `solve`                   | Equations      |
| Vectors    | `norm`                    | Distance       |
| Eigen      | `eig`                     | Directions     |
| SVD        | `svd`                     | Dimensionality |
| QR         | `qr`                      | Factorization  |


USED IN:

- Linear Regression → `solve`, `inv`
- Deep Learning → `dot`, `@`
- PCA → `eig`, `svd`
- Optimization → `norms`
