# **Phase 5 — Mathematical Function**

The Idea

NumPy lets you:

- Aggregate data (sum, mean, etc.)
- Analyze distribution (std, var)
- Apply math functions fast
- Work without loops

Base Arrays

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# **1️⃣ Aggregation Functions**

1️⃣ `np.sum()`

In [3]:
print(np.sum(arr1))
print(np.sum(arr2))
print(np.sum(arr2, axis=0))
print(np.sum(arr2, axis=1))

15
21
[5 7 9]
[ 6 15]


Understanding `axis`

| Axis   | Meaning     |
| ------ | ----------- |
| axis=0 | column-wise |
| axis=1 | row-wise    |


2️⃣ `np.mean()`

In [4]:
print(np.mean(arr1))
print(np.mean(arr2))
print(np.mean(arr2, axis=0))
print(np.mean(arr2, axis=1))

3.0
3.5
[2.5 3.5 4.5]
[2. 5.]


3️⃣ `np.median()`

In [5]:
print(np.median(arr1))
print(np.median(arr2))

3.0
3.5


4️⃣ `np.std()` (Standard Deviation)

In [ ]:
print(np.std(arr1))
print(np.std(arr2))

[10. 10. 10.]


measures spread of data

5️⃣ `np.var()` (Variance)

In [6]:
print(np.var(arr1))
print(np.var(arr2))

2.0
2.9166666666666665


variance = std²

**Aggregation Table**

| Function | Meaning        |
| -------- | -------------- |
| sum      | total          |
| mean     | average        |
| median   | middle value   |
| std      | spread         |
| var      | spread squared |



# **2️⃣ Min & Max**

In [9]:
print(np.min(arr1))
print(np.max(arr1))

print(np.min(arr2))
print(np.max(arr2))

print(np.min(arr2, axis=0))
print(np.max(arr2, axis=0))

print(np.min(arr2, axis=1))
print(np.max(arr2, axis=1))

1
5
1
6
[1 2 3]
[4 5 6]
[1 4]
[3 6]


**Table**
| Function | Result         |
| -------- | -------------- |
| min      | smallest value |
| max      | largest value  |


# **3️⃣ Mathematical Functions (Element-wise)**

1️⃣ Square Root

In [11]:
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [12]:
print(np.sqrt(arr2))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


2️⃣ Exponential

In [13]:
print(np.exp(arr1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [14]:
print(np.exp(arr2))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


3️⃣ Logarithm

In [15]:
print(np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [16]:
print(np.log(arr2))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


4️⃣ More Examples


In [17]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


**Table**

| Function | Meaning     |
| -------- | ----------- |
| sqrt     | square root |
| exp      | e^x         |
| log      | ln(x)       |


# **4️⃣ Trigonometric Functions**



In [18]:
arr = np.array([0, np.pi/2, np.pi])
print(arr)

[0.         1.57079633 3.14159265]


In [19]:
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


⚠️**Important Note**: NumPy uses radians NOT degrees

Convert degrees → radians

In [21]:
print(np.deg2rad(90))

1.5707963267948966


Table

| Function | Meaning |
| -------- | ------- |
| sin      | sine    |
| cos      | cosine  |
| tan      | tangent |


# **5️⃣ Rounding Functions**

In [22]:
arr = np.array([1.2, 2.5, 3.7])
print(arr)

[1.2 2.5 3.7]


1️⃣ `np.round()`

In [23]:
print(np.round(arr))

[1. 2. 4.]


2️⃣ `np.floor()`

In [25]:
print(np.floor(arr))

[1. 2. 3.]


3️⃣ `np.ceil()`

In [24]:
print(np.ceil(arr))

[2. 3. 4.]


**Table**

| Function | Result  |
| -------- | ------- |
| round    | nearest |
| floor    | down    |
| ceil     | up      |


# **FULL COMBINED EXAMPLE**

In [26]:
arr = np.arange(1,10).reshape(3,3)

print(f"Sum: {np.sum(arr)}\n")
print(f"Mean: {np.mean(arr)}\n")
print(f"Std: {np.std(arr)}\n")

print(f"Min: {np.min(arr)}\n")
print(f"Max: {np.max(arr)}\n")

print(f"Sqrt:\n {np.sqrt(arr)}\n")
print(f"Log:\n {np.log(arr)}\n")

print(f"Round:\n {np.round(np.sqrt(arr))}\n")

Sum: 45

Mean: 5.0

Std: 2.581988897471611

Min: 1

Max: 9

Sqrt:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

Log:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

Round:
 [[1. 1. 2.]
 [2. 2. 2.]
 [3. 3. 3.]]



# **COMPARISON**
| Category    | Functions          |
| ----------- | ------------------ |
| Aggregation | sum, mean, median  |
| Spread      | std, var           |
| Min/Max     | min, max           |
| Math        | sqrt, exp, log     |
| Trig        | sin, cos, tan      |
| Rounding    | round, floor, ceil |


# **🧠 HOW TO THINK**
| Goal           | Use         |
| -------------- | ----------- |
| total          | sum         |
| average        | mean        |
| spread         | std         |
| middle value   | median      |
| transform data | sqrt/log    |
| clean numbers  | round/floor |


# **Practice**

```
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

# 1. Sum each column
# 2. Mean of each row
# 3. Find max in each column
# 4. Apply sqrt to all values
# 5. Round the result
```

In [27]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

# 1. Sum each column
print(f"Sum: {np.sum(arr, axis=0)}\n")

# 2. Mean of each row
print(f"Mean{np.mean(arr, axis=1)}\n")

# 3. Find max in each column
print(f"Max: {np.max(arr, axis=0)}\n")

# 4. Apply sqrt to all values
print(f"Sqrt: {np.sqrt(arr)}\n")

# 5. Round the result
print(f"Round:\n {np.round(np.sqrt(arr))}\n")

Sum: [50 70 90]

Mean[20. 50.]

Max: [40 50 60]

Sqrt: [[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]

Round:
 [[3. 4. 5.]
 [6. 7. 8.]]



# **FINAL CHEAT SHEET**

| Category    | Functions          |
| ----------- | ------------------ |
| Aggregation | sum, mean, median  |
| Spread      | std, var           |
| Range       | min, max           |
| Math        | sqrt, exp, log     |
| Trig        | sin, cos, tan      |
| Rounding    | round, floor, ceil |
