# **Phase 1 — NumPy Foundations**

# **1️⃣ What is NumPy & Why It’s FAST**

NumPy = Numerical Python → library for working with arrays and numerical computation.

------------------------------
**Why NumPy is FAST**

Key Idea: Continuous Memory

1- Python list → scattered in memory

`list = [1, 2, 3]`

Stored as:

`[ pointer → 1 ] [ pointer → 2 ] [ pointer → 3 ]`

2- NumPy array → stored in one continuous block

`
import numpy as np
arr = np.array([1, 2, 3])
`

Stored as:

`[ 1 ][ 2 ][ 3 ]`

Direct continuous block → faster access + better cache usage

**Comparison**

| Feature       | Python List | NumPy Array    |
| ------------- | ----------- | -------------- |
| Memory layout | Scattered   | Continuous     |
| Speed         | Slow        | Fast           |
| Data type     | Mixed       | Same type only |
| Operations    | Loop needed | Vectorized     |

-------------------------------

**Speed Comparison**


In [1]:
import numpy as np
import time

# Python list
lst = list(range(1000000))
start = time.time()
lst = [x * 2 for x in lst]
print("List time:", time.time() - start)

# NumPy
arr = np.arange(1000000)
start = time.time()
arr = arr * 2
print("NumPy time:", time.time() - start)

List time: 0.07017064094543457
NumPy time: 0.0037975311279296875


# **2️⃣ nparray vs Python List**

| Feature         | list        | nparray     |
| --------------- | ----------- | ----------- |
| Type            | Flexible    | Fixed dtype |
| Speed           | Slow        | Fast        |
| Math operat
ions | Manual      | Built-in    |
| Memory          | Inefficient | Efficient   |

Example 1: Mixed Types
- Allowed in list
- Not allowed in NumPy


In [2]:
# Python list (mixed types)
list = [1, "hello", 3.5]
print(list)

# NumPy (forced same type)
arr = np.array([1,2,3])
print(arr.dtype)

[1, 'hello', 3.5]
int64


Type Conversion Example

In [3]:
arr = np.array([1,2,3.5])
print(arr)
print(arr.dtype)

[1.  2.  3.5]
float64


Nested Structure Difference

In [ ]:
# Python list
list = [[1, 2], [3, 4, 5]]  # allowed
print(list)
# NumPy
arr = np.array([[1, 2], [3, 4]])  # must be same shape

# **3️⃣ Creating Arrays (ALL CASES)**

**1️⃣ np.array()**

In [4]:
# 1D
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# 2D
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
# 3D
a = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Force dtype

In [7]:
a = np.array([1,2,3], dtype=float)
print(a)

[1. 2. 3.]


Copy vs Reference

In [10]:
a = np.array([1, 2, 3])
b = np.array(a)   # copy

print(f"a before change {a}")

a[0] = 100

print(f"b array {b}")  # unchanged
print(f"a after change {a}")

a before change [1 2 3]
b array [1 2 3]
a after change [100   2   3]


**2️⃣ np.zeros()**

In [12]:
# 1D
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [13]:
# 2D
a = np.zeros((2,3)) # 2 rows * 3 columns
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# 3D
a = np.zeros((2,3,4)) # (2) number of 2D matrices stacked,3 rows * 4 columns
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [15]:
a = np.zeros((2,2), dtype=int)
print(a)

[[0 0]
 [0 0]]


**3️⃣ np.ones()**

In [18]:
# 1D
a = np.ones(4)
print(a)

[1. 1. 1. 1.]


In [23]:
# 2D
a = np.ones((3,2)) # 3 rows * 2 columns
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
# 3D
a = np.ones((3,2,2)) # (3) number of 2D matrices stacked, 2 rows * 2 columns
print(a)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [24]:
a = np.ones((3,3), dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


**Comparison**
| Function | Purpose     |
| -------- | ----------- |
| zeros()  | Fill with 0 |
| ones()   | Fill with 1 |


**4️⃣ 4. np.full()**

In [26]:
# 1D
a = np.full(5, 6)
print(a)

[6 6 6 6 6]


In [27]:
# 2D
a = np.full((2, 2), 7)
print(a)

[[7 7]
 [7 7]]


In [28]:
# 2D
a = np.full((3, 4), -1)
print(a)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [29]:
# 2D
a = np.full((2, 2), 3.14)
print(a)

[[3.14 3.14]
 [3.14 3.14]]


In [30]:
# 3D
a = np.full((2, 2, 2), 8)
print(a)

[[[8 8]
  [8 8]]

 [[8 8]
  [8 8]]]


**5️⃣ np.eye() (Identity Matrix)**

- a special kind of square matrix where all the diagonal elements are 1 and all other elements are 0.


In [31]:
a = np.eye(3) # 3 rows * 3 columns
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
a = np.eye(3, k=0) # main diagonal
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
a = np.eye(3, k=1)   # above diagonal
print(a)


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [33]:
a = np.eye(3, k=-1)  # below diagonal
print(a)


[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


**Comparison**
| Function | Output          |
| -------- | --------------- |
|  full()  | Fill with value |
|  eye()   | Identity matrix |


**6️⃣ np.arange()**

In [36]:
a = np.arange(10) # range
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
a = np.arange(2,10) # from 2 to 10
print(a)

[2 3 4 5 6 7 8 9]


In [38]:
a = np.arange(2, 10, 2) # from 2 to 10 with 2 step each time until 10
print(a)

[2 4 6 8]


In [39]:
a = np.arange(0, 1, 0.1) # from 0 to 1 with 0.1 step each time until 1
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


**7️⃣ np.linspace()**

In [41]:
a = np.linspace(0, 10, 5) # from 0 to 10 and give me 5 values only
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [42]:
a = np.linspace(0, 1, 10) # from 0 to 1 and give me 10 values only
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [43]:
a = np.linspace(0, 100, 50) # from 0 to 100 and give me 50 values only
print(a)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


**Comparison**

| Feature       | arange | linspace         |
| ------------- | ------ | ---------------- |
| Based on      | step   | number of values |
| Includes end? | ❌      | ✅                |


# **4️⃣ Random Functions 🎲**

**1️⃣ Random values 🎲**

In [44]:
# 1D
a = np.random.rand(3)
print(a)

[0.93949925 0.84829693 0.7501506 ]


In [45]:
# 2D
a = np.random.rand(2,3)
print(a)

[[0.78690144 0.51071129 0.17850288]
 [0.71076089 0.2307535  0.56413464]]


In [46]:
# 3D
a = np.random.rand(2,3,3)
print(a)

[[[0.18305316 0.0778197  0.93505023]
  [0.05432306 0.1219595  0.15896934]
  [0.39127948 0.24502683 0.9656342 ]]

 [[0.53954456 0.58086494 0.58804741]
  [0.60409384 0.4727574  0.79889838]
  [0.31554815 0.42299593 0.93419289]]]


**2️⃣ Random integers 🎲**

In [47]:
a = np.random.randint(0,10) # give you random integers 0 to 10
print(a)

2


In [50]:
# 1D
a = np.random.randint(0,10, size=5) # create 1D array of 5 random integers from 0 to 9
print(a)

[8 2 7 9 2]


In [51]:
# 2D
a = np.random.randint(0, 10, size=(2,3)) # 2D array (2 rows × 3 columns) of random integers 0–9
print(a)

[[4 7 5]
 [3 6 1]]


In [53]:
# 3D
a = np.random.randint(0, 10, size=(2,3,3)) # 3D array (2 blocks × 3 rows × 3 columns) of random integers 0–9
print(a)

[[[2 9 3]
  [0 0 0]
  [0 5 9]]

 [[9 3 2]
  [7 0 2]
  [7 7 4]]]


**3️⃣ Normal distribution 🎲**

In [54]:
a = np.random.randn(3) # 1D array of 3 random numbers from standard normal distribution
print(a)

[-0.05649402 -1.03124924 -1.13016603]


In [55]:
a = np.random.randn(2,2) # 2D array (2×2) of random numbers from standard normal distribution
print(a)

[[ 0.77276884  2.18724642]
 [-1.63030861 -0.21183075]]


In [57]:
a = np.random.randn(3,2,2)  # 3D array (3 blocks × 2 rows × 2 columns) of random numbers from standard normal distribution
print(a)

[[[ 0.4317634   0.42093799]
  [ 0.36262894 -0.635059  ]]

 [[ 1.01793892  0.55679678]
  [ 2.11479735 -0.13718415]]

 [[-1.60235462  1.79770885]
  [ 1.03138241  1.59845637]]]


**4️⃣ Choice 🎲**

In [58]:
a = np.random.choice([1,2,3,4]) # Pick one random element from [1,2,3,4]
print(a)

1


In [59]:
a = np.random.choice([1,2,3], size=5)  # Create 1D array of 5 random picks from [1,2,3]
print(a)

[2 3 2 3 1]


In [60]:
a = np.random.choice([1,2,3], size=5, p=[0.1,0.3,0.6])  # Create 1D array of 5 random picks from [1,2,3] with given probabilities
print(a)

[3 3 2 3 3]


In [61]:
a = np.random.choice([1,2,3], size=(5,3))  # Create 2D array (5 rows × 3 cols) of random picks from [1,2,3]
print(a)

[[1 1 2]
 [2 3 2]
 [1 3 3]
 [3 1 3]
 [1 3 1]]


In [63]:
a = np.random.choice([1,2,3], size=(5,5), p=[0.1,0.3,0.6])  # Create 2D array (5×5) of random picks from [1,2,3] with given probabilities
print(a)

[[2 2 1 3 2]
 [3 3 2 2 2]
 [1 3 3 1 2]
 [2 2 3 3 1]
 [2 3 3 3 2]]


In [64]:
a = np.random.choice([1,2,3], size=(2,3,3))  # Create 3D array (2 blocks × 3 rows × 3 cols) of random picks from [1,2,3]
print(a)

[[[2 2 2]
  [1 2 3]
  [1 3 1]]

 [[1 2 3]
  [1 3 1]
  [3 1 3]]]


In [65]:
a = np.random.choice([1,2,3], size=(2,3,3), p=[0.1,0.3,0.6])  # Create 3D array (2×3×3) of random picks with given probabilities
print(a)

[[[2 2 3]
  [3 3 3]
  [2 3 3]]

 [[3 3 3]
  [2 3 3]
  [3 3 3]]]


**5️⃣ Shuffle 🎲**

In [69]:
arr = np.array([1,2,3,4])
np.random.shuffle(arr)  # shuffle elements of arr in place
print(arr)

[3 2 4 1]


**6️⃣ Seed (IMPORTANT for reproducibility) 🎲**

- This ensures you get the same random numbers every time you run the code.


In [72]:
np.random.seed(42) # set random seed for reproducibility
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

**Comparison**

| Function | Meaning                    |
| -------- | -------------------------- |
| rand     | uniform (0–1)              |
| randn    | normal distribution        |
| randint  | integers                   |
| choice   | random selection           |
| shuffle  | shuffle array (in-place)   |
| seed     | fix randomness (reproduce) |


# **5️⃣ Data Types (dtype)**

What is dtype?

Every NumPy array has one fixed type

**1️⃣ Check dtype**

In [78]:
arr = np.array([1,2,3])
print(arr.dtype)

int64


**2️⃣ Common types**

In [ ]:
np.array([1,2,3], dtype=np.int32)
np.array([0.1, 2.2, 6.3], dtype=np.float64)
np.array([1,0,1], dtype=bool)
np.array(['a','b'], dtype=str)

**3️⃣ Convert dtype**

In [83]:
arr = np.array([1,2,3])
print(f"before convert: {arr.dtype}")
arr = arr.astype(float)
print(f"after convert: {arr.dtype}")

before convert: int64
after convert: float64


**4️⃣ Memory size**

In [84]:
arr = np.array([1,2,3], dtype=np.int32)
print(f"bytes per element: {arr.itemsize}")  # bytes per element
print(f"total bytes: {arr.nbytes}")    # total bytes

bytes per element: 4
total bytes: 12


**Common Types**
| Type              | Meaning    |
| ----------------- | ---------- |
| int32 / int64     | integers   |
| float32 / float64 | decimals   |
| bool              | True/False |
| object            | mixed      |
